# Playbook Atelier 1 : Python pour Microsoft Fabric

Parties en Markdown, cellules de code, interprétation sous chaque cellule. Exécuter depuis le dossier `formation_python_fabric` (contenant `data/`). Les cellules « Étape manuelle » créent automatiquement les fichiers que les apprenants créent dans l'Explorateur.

# PARTIE 2 : LES BASES DU LANGAGE

Chaque bloc de code ci-dessous se saisit dans **une cellule** du notebook `atelier1_langage`, dans l'ordre. **Les commentaires (`#`) font partie de l'explication : lisez-les avant d'exécuter.**

## 📝 Cellule 1 : Vérification de l'environnement et techniques d'importation

In [1]:
# === CELLULE 1 : Vérification de l'environnement et techniques d'importation ===

# Technique 1 : « import module ». On garde le nom complet : on écrira ensuite « sys.version ».
import sys

# Technique 2 : « import module as alias ». On donne un nom court au module.
# C'est l'usage courant pour les bibliothèques de données (« import pandas as pd »).
import platform as pf

# Technique 3 : « from module import objet ». On importe UN objet précis, utilisable sans préfixe.
from pathlib import Path

# Technique 4 : « from module import objet as alias ». Comme la 3, avec un autre nom
# (utile quand deux modules proposent le même nom).
from datetime import datetime as dt

# Technique 5 : « import paquet.sous_module ». Un paquet est un dossier de modules ; on écrira « os.path.xxx ».
import os.path

# Technique 6 : import à partir d'un TEXTE. Utile quand le nom du module vient d'un fichier de configuration.
from importlib import import_module
module_json = import_module("json")

# ❌ À éviter : « from module import * » importe tous les noms d'un coup et peut écraser vos propres variables.

# --- Vérification de l'environnement (utilise les imports ci-dessus)
print(f"Python         : {sys.version.split()[0]}")             # technique 1 : préfixe « sys. »
print(f"Implémentation : {pf.python_implementation()}")          # technique 2 : alias « pf »
print(f"Système        : {pf.system()} {pf.machine()}")
print(f"Interpréteur   : {sys.executable}")                       # le Python qui exécute cette cellule
print(f"Dossier actif  : {Path.cwd()}")                           # technique 3 : « Path » sans préfixe
print(f"Dans un venv   : {sys.prefix != sys.base_prefix}")        # True si un environnement virtuel est actif

# --- Les autres techniques en action
print(dt(2025, 1, 3).strftime("%d/%m/%Y"))                        # technique 4 : alias « dt »
print(os.path.basename("data/sites_reference.csv"))               # technique 5 : os.path.xxx
print(module_json.dumps({"site": "SITE_IND_001"}))                # technique 6 : module obtenu par son nom

Python         : 3.12.x
Implémentation : CPython
Système        : Windows AMD64
Interpréteur   : C:\Users\formation\formation_python_fabric\.venv\Scripts\python.exe
Dossier actif  : C:\Users\formation\formation_python_fabric
Dans un venv   : True
03/01/2025
sites_reference.csv
{"site": "SITE_IND_001"}


### 💡 Interprétation : Cellule 1, Vérification de l'environnement et techniques d'importation

- **Version** : 3.11 ou plus est nécessaire ; sinon `tomllib`, `StrEnum` et `except*` (vus plus loin) échoueront.
- **Chemin de l'interpréteur** : il doit passer par `.venv`. Si `Dans un venv` vaut `False`, le notebook n'utilise pas votre environnement : relancez `jupyter notebook` depuis un terminal où `.venv` est activé.
- **Préfixe ou pas** : avec `import sys`, on écrit `sys.version` ; avec `from pathlib import Path`, on écrit `Path` seul. Le préfixe indique d'où vient le nom, ce qui aide à relire le code.
- **Alias** : `pf` et `dt` sont des noms locaux ; ils n'existent que dans **votre** notebook.
- **`import *`** : il rend impossible de savoir d'où vient un nom ; les équipes le proscrivent.
- **Dans Fabric** : `sys.version` identifie le runtime (Runtime 1.3 : Python 3.11 ; Runtime 2.0 : Python 3.13).

## 📝 Cellule 2 : Premier contact : `print`, commentaires, indentation

In [1]:
# === CELLULE 2 : print, commentaires, indentation ===
# Ceci est un commentaire : Python l'ignore.

print("Réseau EnergiaNord : 6 sites")                 # affichage simple, retour à la ligne automatique

# sep : ce qui sépare les éléments (par défaut un espace)
print("Site", "SITE_IND_001", "5.0 MW", sep=" | ")   # affiche : Site | SITE_IND_001 | 5.0 MW

# end : ce qui termine la ligne (par défaut un retour à la ligne)
print("Chargement...", end=" ")                       # reste sur la même ligne
print("terminé")                                      # complète la ligne précédente

# Des parenthèses permettent de couper une longue instruction sur plusieurs lignes
message = ("Mesures toutes les 15 minutes "
           "sur 6 sites")
if len(message) > 20:                                 # len() compte les caractères ; la ligne finit par « : »
    print(f"Message de {len(message)} caractères")    # ligne indentée = dans le bloc du « if »

Réseau EnergiaNord : 6 sites
Site | SITE_IND_001 | 5.0 MW
Chargement... terminé
Message de 41 caractères


### 💡 Interprétation : Cellule 2, Premier contact : `print`, commentaires, indentation

- **`sep` et `end`** : ils remplacent les astuces de ponctuation de Python 2 (la virgule finale).
- **Le `:` et l'indentation** : c'est la seule « ponctuation » structurelle du langage ; pas d'accolades ni de `end`.
- **Piège fréquent** : du code collé depuis un e-mail ou un site web perd souvent son indentation ; l'erreur n'apparaît qu'à l'exécution (`IndentationError`).
- **`len(message)`** : 34 caractères, donc le test `> 20` est vrai et la ligne s'affiche.

## 📝 Cellule 3 : Variables et typage dynamique

In [2]:
# === CELLULE 3 : Variables et typage dynamique ===

# Création de cinq variables : on écrit « nom = valeur »
site_id = "SITE_IND_001"       # texte (str)
capacity_mw = 5.0              # nombre décimal (float)
flexible = True                # booléen (bool) : True ou False, avec une majuscule
nb_mesures = 720               # nombre entier (int)
curtailment_price = None       # None : ce site n'a pas de prix d'effacement

# Affichage : pour chaque variable, son nom, sa valeur et son type
# (« !r » montre la valeur telle qu'on l'écrirait en code, avec les guillemets pour un texte)
for nom, valeur in [("site_id", site_id), ("capacity_mw", capacity_mw),
                    ("flexible", flexible), ("nb_mesures", nb_mesures),
                    ("curtailment_price", curtailment_price)]:
    print(f"{nom:<18} {valeur!r:<16} {type(valeur).__name__}")

# Typage dynamique : le même nom peut désigner, plus tard, une valeur d'un autre type
x = 10                         # x désigne un entier
x = "dix"                      # x désigne maintenant un texte : c'est autorisé
print(type(x).__name__)        # str

# Un booléen est aussi un entier : True vaut 1 et False vaut 0
print(isinstance(flexible, int))   # True : « flexible » (un bool) est reconnu comme un int

site_id            'SITE_IND_001'   str
capacity_mw        5.0              float
flexible           True             bool
nb_mesures         720              int
curtailment_price  None             NoneType
str
True


### 💡 Interprétation : Cellule 3, Variables et typage dynamique

- **Typage dynamique** : le type est connu à l'**exécution**, et un même nom peut changer de type (`x` : `int` puis `str`).
- **Typage fort** : Python ne mélange pas les types en silence ; `"dix" + 1` est refusé.
- **`None`** : s'affiche `None` avec le type `NoneType` ; à distinguer de `0` et de `""`.
- **`isinstance(flexible, int)` vaut `True`** : `bool` est un cas particulier de `int` (`True == 1`). En pandas, une colonne de booléens peut donc entrer dans un calcul numérique.

## 📝 Cellule 4 : Nombres : division, flottants, `Decimal`

In [3]:
# === CELLULE 4 : Nombres — division, flottants, Decimal ===
import math
from decimal import Decimal

# --- 1) Les opérateurs arithmétiques
print(7 / 2)       # 3.5   : « / » donne toujours un nombre décimal
print(7 // 2)      # 3     : « // » donne la division entière (quotient)
print(7 % 2)       # 1     : « % » donne le reste de la division
print(2 ** 10)     # 1024  : « ** » élève à la puissance

# --- 2) Le piège des nombres décimaux (float)
somme = 0.1 + 0.2                                  # on additionne deux décimaux
print("0.1 + 0.2 vaut          :", somme)          # 0.30000000000000004 : un minuscule écart apparaît
print("0.1 + 0.2 == 0.3 ?      :", somme == 0.3)   # False : la comparaison exacte échoue à cause de cet écart

# À la place de « == », on compare avec une tolérance
print("math.isclose(somme, 0.3):", math.isclose(somme, 0.3))   # True : l'écart infime est accepté

# --- 3) Decimal : calcul exact, pour les montants
# On lui passe des TEXTES (« "0.1" »), pas des décimaux, pour éviter l'erreur de départ.
print("Decimal :", Decimal("0.1") + Decimal("0.2"))            # 0.3 exactement

3.5
3
1
1024
0.1 + 0.2 vaut          : 0.30000000000000004
0.1 + 0.2 == 0.3 ?      : False
math.isclose(somme, 0.3): True
Decimal : 0.3


### 💡 Interprétation : Cellule 4, Nombres : division, flottants, `Decimal`

- **Les trois divisions** : `7 / 2` = `3.5`, `7 // 2` = `3`, `7 % 2` = `1`. L'ambiguïté de Python 2 (où `7 / 2` donnait `3`) a disparu.
- **`0.1 + 0.2`** : le résultat est `0.30000000000000004`, donc la comparaison `== 0.3` est **fausse**. Ce n'est pas un bug de Python : c'est la limite du calcul binaire.
- **Même comportement partout** : pandas, NumPy et Spark ont le même écart ; les calculs du réseau EnergiaNord sont concernés.
- **Règle** : comparer avec `math.isclose` (ou une tolérance), jamais avec `==`.
- **`Decimal("0.1") + Decimal("0.2")`** : donne exactement `0.3` ; à réserver aux montants, car plus lent que `float`.

## 📝 Cellule 5 : Nombres : arrondi, grands entiers, `NaN` et `None`

In [4]:
# === CELLULE 5 : Arrondi, grands entiers, NaN et None ===

# --- Arrondi : au pair le plus proche quand la décimale est exactement 5
print(round(0.5), round(1.5), round(2.5), round(3.5))   # 0 2 2 4 : 0.5 -> 0 (pair), 1.5 -> 2, 2.5 -> 2 (pair), 3.5 -> 4
print(round(2.675, 2))          # 2.67 (et non 2.68) : 2.675 est stocké en binaire un peu en dessous de 2.675

# --- Grands nombres
print(1_000_000 * 1.5)          # 1500000.0 : le « _ » est ignoré, il sert seulement à la lecture
print(2 ** 100)                 # un entier de 31 chiffres : aucune limite de taille

# --- NaN : un résultat indéfini
valeur_nan = float("nan")                               # on crée un NaN à partir du texte "nan"
print(valeur_nan == valeur_nan)                         # False : un NaN n'est égal à rien, pas même à lui-même
print(math.isnan(valeur_nan))                           # True : c'est la bonne façon de le détecter

# --- None : l'absence de valeur
print(None == 0)                                        # False : None n'est pas zéro
print(None is None)                                     # True : on teste None avec « is »

0 2 2 4
2.67
1500000.0
1267650600228229401496703205376
False
True
False
True


### 💡 Interprétation : Cellule 5, Nombres : arrondi, grands entiers, `NaN` et `None`

- **`0 2 2 4`** : ce résultat surprend beaucoup de participants ; c'est l'arrondi « au pair » de Python.
- **Point d'attention Fabric** : `round` de **Python et de pandas** arrondit au pair, alors que `round` de **Spark SQL** arrondit « demi vers le haut » (`HALF_UP`). Spark propose `bround` pour l'arrondi au pair. Un même calcul peut donc différer entre un notebook pandas et un notebook PySpark.
- **`round(2.675, 2)` = `2.67`** : `2.675` n'est pas représentable exactement en binaire (même cause qu'à la cellule précédente).
- **`NaN`** : `valeur_nan == valeur_nan` est `False` ; on le détecte avec `math.isnan` (ou `isna()` en pandas), jamais avec `==`.
- **`None`** : ni égal à `0`, ni à `""` ; on le teste avec `is None`.

## 📝 Cellule 6 : Constantes

In [11]:
# === CELLULE 6 : Constantes, Final et MappingProxyType ===
from types import MappingProxyType
from typing import Final

# Une constante « par convention » : nom en MAJUSCULES, annotée « Final » pour les outils d'analyse
CAPACITE_MAX_MW: Final = 5.0

# Un tuple : une séquence qui ne peut pas être modifiée après sa création (parenthèses)
SITES_FLEXIBLES = ("SITE_IND_001", "SITE_IND_002", "SITE_RES_001", "SITE_RES_002")

# Un dictionnaire en lecture seule : associe un code d'erreur à sa signification
CODES_ERREUR = MappingProxyType({
    -999: "Capteur hors service",
    -888: "Valeur non transmise",
    -777: "Recalibrage en cours",
})

# Test 1 : réaffecter une constante « Final » -> Python l'accepte (seul un outil d'analyse protesterait)
CAPACITE_MAX_MW = 6.0
print(CAPACITE_MAX_MW)                    # 6.0

# Test 2 : modifier un dictionnaire en lecture seule -> Python refuse (TypeError)
try:
    CODES_ERREUR[-1] = "test"
except TypeError as erreur:
    print(f"Modification refusée : {erreur}")

6.0
Modification refusée : 'mappingproxy' object does not support item assignment


### 💡 Interprétation : Cellule 6, Constantes

- **`6.0` s'affiche** : Python a accepté la réaffectation de `CAPACITE_MAX_MW`. Seul un vérificateur de types l'aurait signalée.
- **`CODES_ERREUR` refuse la modification** : la protection est **réelle** avec `MappingProxyType` (et les tuples).
- **Dans un notebook Fabric** : ces constantes forment la **cellule de configuration** en tête (noms de tables, chemins du Lakehouse, seuils métier).
- **Réutilisation** : `CODES_ERREUR` sera utilisé à plusieurs reprises dans la suite.

## 📝 Cellule 7 : Énumérations : `StrEnum`

In [5]:
# === CELLULE 7 : StrEnum ===
from enum import Enum, StrEnum

# Hier : on combine « str » et « Enum » pour obtenir une énumération de textes
class StatutAncien(str, Enum):
    OK = "OK"
    ERROR = "ERROR"

# Aujourd'hui (Python 3.11+) : StrEnum fait la même chose en plus simple
class Statut(StrEnum):
    OK = "OK"            # le nom (OK) et la valeur ("OK") du membre
    ERROR = "ERROR"

print(str(StatutAncien.OK), "|", str(Statut.OK))     # StatutAncien.OK | OK : l'affichage diffère

# Un membre StrEnum est un vrai texte : on peut le comparer à une chaîne
print(Statut.OK == "OK")                             # True
print(Statut("ERROR") is Statut.ERROR)               # True : on retrouve un membre à partir de sa valeur

# Dans une f-string, on obtient directement le texte ; « [s.value for s in Statut] » liste les valeurs
print(f"{Statut.ERROR} / {[s.value for s in Statut]}")

StatutAncien.OK | OK
True
True
ERROR / ['OK', 'ERROR']


### 💡 Interprétation : Cellule 7, Énumérations : `StrEnum`

- **Ancienne forme** : `str(StatutAncien.OK)` donne `StatutAncien.OK`.
- **`StrEnum`** : `str(Statut.OK)` donne `OK`, ce qui se prête mieux à l'affichage, aux fichiers et aux requêtes.
- **Comparaison** : `Statut.OK == "OK"` est vrai, on peut donc comparer avec les valeurs lues dans un CSV.
- **Compatibilité** : ✅ `StrEnum` existe dès Python 3.11, donc sur le Runtime Spark 1.3.

## 📝 Cellule 8 : Chaînes : découpage et méthodes

In [8]:
# === CELLULE 8 : Chaînes — découpage et méthodes ===

# Une ligne du fichier CSV, avec des espaces parasites au début et à la fin
ligne = "  2025-01-03T04:30:00,SITE_IND_002,0.865,234.6,49.89,OK  "

# strip() retire les espaces des extrémités ; split(",") coupe la ligne à chaque virgule -> une liste de 6 champs
champs = ligne.strip().split(",")
print(champs)

# Dépaquetage : 6 noms à gauche, 6 valeurs à droite, affectées dans l'ordre
timestamp, site_id, conso, tension, freq, statut = champs

# Découpage : [début:fin], avec une fin exclue ; les indices négatifs comptent depuis la fin
print(site_id[:8])       # SITE_IND : les 8 premiers caractères
print(site_id[-3:])      # 002      : les 3 derniers
print(site_id[::-1])     # 200_DNI_ETIS : le texte à l'envers

# Quelques méthodes : chacune renvoie une NOUVELLE chaîne (site_id n'est pas modifié)
print(site_id.lower())                    # site_ind_002
print(site_id.replace("_", "-"))          # SITE-IND-002
print(site_id.startswith("SITE_"))        # True
print(site_id.removeprefix("SITE_"))      # IND_002 : retire le début exact « SITE_ »
print(site_id.removesuffix("_002"))       # SITE_IND : retire la fin exacte « _002 »

['2025-01-03T04:30:00', 'SITE_IND_002', '0.865', '234.6', '49.89', 'OK']
SITE_IND
002
200_DNI_ETIS
site_ind_002
SITE-IND-002
True
IND_002
SITE_IND


### 💡 Interprétation : Cellule 8, Chaînes : découpage et méthodes

- **Immuable** : `site_id.lower()` ne change pas `site_id` ; il renvoie une copie.
- **`split(",")`** : transforme la ligne CSV en liste de 6 champs.
- **Dépaquetage** : `timestamp, site_id, ... = champs` affecte les six champs d'un coup ; c'est ce que fera `csv.DictReader` à la Cellule 41.
- **`removeprefix`** : retire exactement `SITE_` ; `lstrip("SITE_")` aurait retiré tous les caractères `S`, `I`, `T`, `E`, `_` en début de texte, ce qui est rarement voulu.

## 📝 Cellule 9 : Chaînes : trois générations de formatage

In [6]:
# === CELLULE 9 : Chaînes — formatage ===
nom, mw = "SITE_IND_001", 2.5

# Trois écritures qui produisent le MÊME texte
print("Site %s : %.2f MW" % (nom, mw))            # Hier : « % » (%s = texte, %.2f = décimal à 2 chiffres)
print("Site {} : {:.2f} MW".format(nom, mw))      # Ensuite : .format(), les {} sont remplis dans l'ordre
print(f"Site {nom} : {mw:.2f} MW")                # Aujourd'hui : f-string, on écrit directement les variables

# {mw=} affiche « mw=2.5 » : le nom ET la valeur (idéal pour déboguer)
print(f"{mw=}")

# Le mini-langage de mise en forme, après les deux-points
print(f"{1234567.891:,.2f} | {0.0345:.1%} | {42:05d} | {nom:>15}")
#      milliers + 2 décimales | pourcentage | zéros devant | aligné à droite sur 15 caractères

# Chaîne « brute » : le préfixe r ignore les séquences d'échappement (\U, \f, \n...)
print(r"C:\Users\formation\data\consommation.csv")

Site SITE_IND_001 : 2.50 MW
Site SITE_IND_001 : 2.50 MW
Site SITE_IND_001 : 2.50 MW
mw=2.5
1,234,567.89 | 3.5% | 00042 |    SITE_IND_001
C:\Users\formation\data\consommation.csv


### 💡 Interprétation : Cellule 9, Chaînes : trois générations de formatage

- **Trois lignes identiques** : seule l'écriture change ; préférer la **f-string**.
- **`{mw=}`** : donne `mw=2.5`, très utile pour déboguer sans réécrire le nom.
- **Mini-langage** : `1,234,567.89`, `3.5%` (0.0345 arrondi à 1 décimale), `00042`, et le nom aligné sur 15 caractères.
- **Chaîne brute `r"..."`** : évite que `\U` ou `\f` soient lus comme des séquences d'échappement ; piège classique avec les chemins Windows.
- **Sécurité** : dans une requête SQL ou un chemin OneLake, n'insérez que des noms maîtrisés, jamais des données externes.
- **Compatibilité** : ⚠️ Python 3.12 autorise `f"{d["cle"]}"` (mêmes guillemets dedans et dehors) ; sur le Runtime 1.3 (Python 3.11), utilisez des guillemets différents.

## 📝 Cellule 10 : Valeurs de vérité et comparaisons

In [7]:
# === CELLULE 10 : Valeurs de vérité et comparaisons ===
conso, capacite = 0.865, 5.0             # deux variables créées en une ligne

# --- Comparaison chaînée : « conso est-elle comprise entre 0 et la capacité ? »
print(0 <= conso <= capacite)            # True

# --- Quelles valeurs sont « vraies » ou « fausses » ? bool(valeur) donne la réponse
valeurs = (0, 0.0, "", [], None, "0", -999)
print([bool(v) for v in valeurs])
# Résultat : les 5 premières sont False (0, 0.0, "", [], None) ; "0" et -999 sont True

# --- == (même contenu) contre is (même objet)
a = [1, 2]
b = [1, 2]                               # une AUTRE liste, qui contient la même chose
print(a == b)                            # True  : même contenu
print(a is b)                            # False : deux objets distincts en mémoire
print(a is not None)                     # True  : la façon correcte de tester « a n'est pas None »

True
[False, False, False, False, False, True, True]
True
False
True


### 💡 Interprétation : Cellule 10, Valeurs de vérité et comparaisons

- **Liste de booléens** : `False, False, False, False, False, True, True` ; `"0"` et `-999` sont **vrais**.
- **Piège pour une mesure** : `if conso:` écarterait un capteur à zéro (valeur légitime) et laisserait passer `-999` (code d'erreur). Pour une mesure, on compare explicitement (`is None`, `>= 0`).
- **`a == b` est vrai, `a is b` est faux** : même contenu, objets différents.
- **`is`** : réservé à `None`, `True` et `False`.
- **Autres mondes** : la même logique de « valeur nulle » existe en pandas (`NaN`, `isna()`) et en SQL (`IS NULL`).

## 📝 Cellule 11 : Opérateurs logiques, `in` et opérateur morse

In [11]:
# === CELLULE 11 : Opérateurs logiques, in et := ===

# --- « or » : valeur de repli. statut est None (faux), donc « or » renvoie le second opérande
statut = None
print(statut or "INCONNU")                       # INCONNU

# --- « in » : appartenance
print("SITE_IND" in "SITE_IND_001")              # True  : ce morceau de texte est dans le texte
print(conso in (-999, -888, -777))               # False : 0.865 n'est pas un code d'erreur

# --- « := » : calculer et garder le résultat dans la même expression
mesures = ["0.865", "abc", "1.2"]
# Sans « := », on écrirait : n = len(mesures) puis, sur la ligne suivante, if n > 2:
if (n := len(mesures)) > 2:                      # len(mesures) est calculé UNE fois, rangé dans n, puis comparé à 2
    print(f"{n} mesures reçues")                 # n est utilisable ici

INCONNU
True
False
3 mesures reçues


### 💡 Interprétation : Cellule 11, Opérateurs logiques, `in` et opérateur morse

- **`statut or "INCONNU"`** : donne `INCONNU` car `None` est faux.
- **Attention** : `or` remplace aussi `0` et `""`. À utiliser quand ces valeurs sont invalides, pas quand elles sont légitimes.
- **`in`** : `"SITE_IND" in "SITE_IND_001"` est vrai ; `0.865 in (-999, -888, -777)` est faux.
- **`:=`** : `len(mesures)` est calculé une seule fois ; `n` reste disponible après le `if`.
- **Usage typique** : boucles de lecture et compréhensions, où le même calcul serait sinon répété.

# PARTIE 3 : STRUCTURES DE CONTRÔLE

## 📝 Cellule 12 : Conditions : `if` / `elif` / `else`

In [8]:
# === CELLULE 12 : Conditions ===

# Deux dictionnaires : capacité de chaque site, et une mesure en MW
capacites = {"SITE_IND_001": 5.0, "SITE_COM_002": 1.5, "SITE_RES_002": 0.6}
mesures = {"SITE_IND_001": 4.6, "SITE_COM_002": 0.4, "SITE_RES_002": 0.61}

# .items() donne, à chaque tour, une clé (le site) et sa valeur (la capacité)
for site_id, capacite in capacites.items():
    taux = mesures[site_id] / capacite          # taux de charge : 1.0 = 100 % de la capacité

    # Les tests sont évalués dans l'ordre : le premier qui est vrai décide.
    if taux > 1:                                # d'abord le cas impossible : la mesure dépasse la capacité
        niveau = "ANOMALIE (dépasse la capacité)"
    elif taux >= 0.8:                           # sinon, très chargé
        niveau = "CRITIQUE"
    elif taux >= 0.5:                           # sinon, chargé
        niveau = "SOUTENU"
    else:                                       # tous les autres cas
        niveau = "NORMAL"

    # Ternaire : « valeur_si_vrai if condition else valeur_si_faux ».
    # startswith accepte un TUPLE de préfixes : vrai si le texte commence par l'un d'eux.
    profil = "flexible" if site_id.startswith(("SITE_IND", "SITE_RES")) else "rigide"

    print(f"{site_id} : {taux:6.1%} -> {niveau:<32} ({profil})")

SITE_IND_001 :  92.0% -> CRITIQUE                         (flexible)
SITE_COM_002 :  26.7% -> NORMAL                           (rigide)
SITE_RES_002 : 101.7% -> ANOMALIE (dépasse la capacité)   (flexible)


### 💡 Interprétation : Cellule 12, Conditions : `if` / `elif` / `else`

- **`SITE_RES_002` dépasse sa capacité** : `0.61 > 0.6`, donc `ANOMALIE`.
- **Ordre des tests** : `taux > 1` doit venir **en premier**. Placé après `>= 0.8`, il aurait été masqué par `CRITIQUE` : l'ordre fait partie de la logique métier.
- **Ternaire** : `profil` prend `flexible` ou `rigide` en une seule ligne.
- **`startswith((...))`** : le tuple évite d'écrire `... or ...`.

## 📝 Cellule 13 : `match` / `case` : hier et aujourd'hui

In [9]:
# === CELLULE 13 : match / case ===

# Hier : une chaîne de if / elif, où « code » est répété à chaque ligne
def decrire_ancien(code):
    if code is None or code == "":
        return "valeur manquante"
    elif code == -999:
        return "capteur hors service"
    elif code == -888 or code == -777:
        return "valeur non transmise ou recalibrage"
    elif isinstance(code, (int, float)) and code >= 0:
        return "mesure valide"
    else:
        return "valeur inattendue"

# Aujourd'hui (3.10+) : match / case. Python compare « code » à chaque motif, de haut en bas.
def decrire(code):
    match code:
        case None | "":                       # « | » : ce motif OU celui-là
            return "valeur manquante"
        case -999:                            # un motif peut être une valeur littérale
            return "capteur hors service"
        case -888 | -777:
            return "valeur non transmise ou recalibrage"
        case int() | float() if code >= 0:    # int() : « est un entier » ; « if » : garde supplémentaire
            return "mesure valide"
        case _:                               # « _ » : tous les autres cas (comme else)
            return "valeur inattendue"

# On vérifie que les deux versions donnent le même résultat sur six valeurs
for valeur in (0.865, -999, -888, None, "", "abc"):
    print(f"{valeur!r:>8} -> {decrire(valeur):<38} identique : {decrire(valeur) == decrire_ancien(valeur)}")

   0.865 -> mesure valide                          identique : True
    -999 -> capteur hors service                   identique : True
    -888 -> valeur non transmise ou recalibrage    identique : True
    None -> valeur manquante                       identique : True
      '' -> valeur manquante                       identique : True
   'abc' -> valeur inattendue                      identique : True


### 💡 Interprétation : Cellule 13, `match` / `case` : hier et aujourd'hui

- **Résultats** : `0.865` → mesure valide, `-999` → capteur hors service, `-888` → non transmise, `None` et `""` → manquante, `"abc"` → inattendue.
- **`identique : True`** sur toutes les lignes : les deux versions se comportent pareil.
- **Lisibilité** : la version `match` se lit comme une table de décision, sans répéter `code ==`.
- **Compatibilité** : ✅ Python 3.10+, donc tous les runtimes Fabric actuels.

## 📝 Cellule 14 : `match` sur un dictionnaire

In [12]:
# === CELLULE 14 : match sur un enregistrement ===
def traiter(enregistrement):
    match enregistrement:
        # Cas 1 : statut ERROR ET une clé consumption_mw, dont la valeur est capturée dans « code »
        #         (la garde « if » vérifie que c'est un code connu de CODES_ERREUR)
        case {"status": "ERROR", "consumption_mw": code} if code in CODES_ERREUR:
            return f"rejet : {CODES_ERREUR[code]}"
        # Cas 2 : statut OK ET une valeur décimale (float), capturée dans « valeur »
        case {"status": "OK", "consumption_mw": float(valeur)}:
            return f"accepté : {valeur} MW"
        # Cas 3 : tout le reste
        case _:
            return "à examiner"

print(traiter({"status": "ERROR", "consumption_mw": -999}))   # cas 1
print(traiter({"status": "OK", "consumption_mw": 1.224}))     # cas 2
print(traiter({"status": "OK"}))                              # cas 3 : la clé consumption_mw manque

rejet : Capteur hors service
accepté : 1.224 MW
à examiner


### 💡 Interprétation : Cellule 14, `match` sur un dictionnaire

- **Premier appel** : `rejet : Capteur hors service` (motif 1, avec `code = -999`).
- **Deuxième appel** : `accepté : 1.224 MW` (motif 2, avec `valeur = 1.224`).
- **Troisième appel** : la clé `consumption_mw` manque ; l'enregistrement tombe dans `case _` **sans erreur** (avec `traiter["consumption_mw"]`, on aurait eu un `KeyError`).
- **Usage** : adapté aux messages JSON de structure variable (événements, API).

## 📝 Cellule 15 : Boucles `for` : `enumerate` et `zip`

In [13]:
# === CELLULE 15 : for, enumerate, zip ===
sites = ["SITE_IND_001", "SITE_IND_002", "SITE_COM_001",
         "SITE_COM_002", "SITE_RES_001", "SITE_RES_002"]
capacites_mw = [5.0, 3.5, 2.0, 1.5, 0.8, 0.6]           # même ordre que « sites »

# enumerate : (numéro, élément) à chaque tour ; start=1 pour compter à partir de 1
for rang, site in enumerate(sites, start=1):
    print(rang, site)

# zip : on lit « sites » et « capacites_mw » en parallèle
for site, cap in zip(sites, capacites_mw):
    print(f"{site} : {cap} MW")

1 SITE_IND_001
2 SITE_IND_002
3 SITE_COM_001
4 SITE_COM_002
5 SITE_RES_001
6 SITE_RES_002
SITE_IND_001 : 5.0 MW
SITE_IND_002 : 3.5 MW
SITE_COM_001 : 2.0 MW
SITE_COM_002 : 1.5 MW
SITE_RES_001 : 0.8 MW
SITE_RES_002 : 0.6 MW


### 💡 Interprétation : Cellule 15, Boucles `for` : `enumerate` et `zip`

- **`enumerate`** : affiche `1 SITE_IND_001` … `6 SITE_RES_002`, sans gérer d'indice à la main.
- **`zip`** : associe chaque site à sa capacité (`SITE_IND_001 : 5.0 MW`, …).
- **Bénéfice** : disparition des erreurs « décalé d'un cran ».
- **Réutilisation** : les listes `sites` et `capacites_mw` servent dans la suite.

## 📝 Cellule 16 : `zip` paresseux et `strict=True`

In [14]:
# === CELLULE 16 : zip paresseux et strict ===
paires = zip(sites, capacites_mw)
print(paires)                           # <zip object ...> : un itérateur, pas une liste
print(list(paires)[:2])                 # list(...) le consomme : les 2 premières paires

# Sans strict : listes de longueurs différentes (6 sites, 4 capacités) -> aucune erreur
print(len(list(zip(sites, capacites_mw[:4]))))     # 4 : deux sites disparaissent en silence

# Avec strict=True : la différence de longueur est détectée
try:
    list(zip(sites, capacites_mw[:4], strict=True))
except ValueError as erreur:
    print(f"ValueError : {erreur}")

[('SITE_IND_001', 5.0), ('SITE_IND_002', 3.5)]
4
ValueError : zip() argument 2 is shorter than argument 1


### 💡 Interprétation : Cellule 16, `zip` paresseux et `strict=True`

- **`<zip object ...>`** : la première ligne montre un itérateur, pas les données.
- **Sans `strict`** : 6 sites deviennent 4 sans aucun message ; un capteur oublié disparaît.
- **Avec `strict=True`** : l'incohérence est **détectée immédiatement** (`ValueError`).
- **Bonne pratique** : `strict=True` par défaut quand les longueurs **doivent** correspondre.

## 📝 Cellule 17 : `break`, `continue`, `else` de boucle, `while`

In [15]:
# === CELLULE 17 : break, continue, else, while ===

# On cherche le premier site de plus de 3 MW, en ignorant les sites de moins de 1 MW
for site, cap in zip(sites, capacites_mw):
    if cap < 1.0:
        continue                                # site trop petit : on passe au suivant
    if cap > 3.0:
        print(f"Premier site > 3 MW : {site}")
        break                                   # trouvé : on quitte la boucle (le « else » ci-dessous est alors sauté)
else:
    print("Aucun site > 3 MW")                  # atteint seulement si la boucle n'a jamais fait « break »

# while : on répète tant que le cumul est inférieur à 10 MWh
cumul_mwh, heure = 0.0, 0
while cumul_mwh < 10:
    cumul_mwh += 2.5                            # +2.5 MWh à chaque heure
    heure += 1
print(f"{cumul_mwh} MWh atteints après {heure} h")

Premier site > 3 MW : SITE_IND_001
10.0 MWh atteints après 4 h


### 💡 Interprétation : Cellule 17, `break`, `continue`, `else` de boucle, `while`

- **Premier tour** : `SITE_IND_001` (5.0 MW) dépasse 3 MW ; la boucle s'arrête (`break`) et le `else` n'est pas exécuté.
- **`for ... else`** : évite une variable « trouvé = True » ; utile pour dire « rien trouvé ».
- **`while`** : le cumul passe par 2.5, 5.0, 7.5, 10.0 ; quatre tours, 4 h.
- **Danger** : si la condition d'un `while` ne devient jamais fausse, la cellule tourne sans fin (menu **Kernel → Interrupt**).

## 📝 Cellule 18 : Compréhensions de liste

In [16]:
# === CELLULE 18 : Compréhensions de liste ===

# Des mesures brutes mélangées : décimaux, codes d'erreur (entiers) et texte vide
mesures_brutes = [0.865, -999, 1.224, "", 0.149, -888, 1.105]

# --- Sans compréhension (4 lignes)
valides = []                                            # 1. on crée une liste vide
for m in mesures_brutes:                                # 2. on parcourt les mesures
    if isinstance(m, float) and m >= 0:                 # 3. on garde les décimaux positifs (isinstance teste le type)
        valides.append(m)                               # 4. on ajoute à la liste

# --- Avec compréhension (1 ligne) : « m pour chaque m de mesures_brutes, si la condition est vraie »
valides = [m for m in mesures_brutes if isinstance(m, float) and m >= 0]
print(valides)                                          # [0.865, 1.224, 0.149, 1.105]

[0.865, 1.224, 0.149, 1.105]


### 💡 Interprétation : Cellule 18, Compréhensions de liste

- **Résultat** : `[0.865, 1.224, 0.149, 1.105]` avec les deux écritures.
- **Pourquoi `-999` est écarté** : c'est un `int`, pas un `float`, donc `isinstance(m, float)` est faux. Le texte vide `""` l'est aussi.
- **Bénéfice** : filtrer, transformer et construire la liste tiennent en **une ligne**.
- **Limite** : au-delà de deux lignes ou d'une logique compliquée, une boucle classique reste plus lisible.

## 📝 Cellule 19 : Compréhensions de dictionnaire et d'ensemble

In [17]:
# === CELLULE 19 : Dictionnaires et ensembles par compréhension ===

# Dictionnaire : pour chaque couple (site, capacité) de zip, on crée « site: capacité »
capacite_par_site = {s: c for s, c in zip(sites, capacites_mw)}
print(capacite_par_site["SITE_COM_001"])           # 2.0 : on retrouve une capacité à partir du site

# Ensemble : « SITE_IND_001 ».split("_") donne ["SITE", "IND", "001"] ; [1] prend "IND"
familles = {s.split("_")[1] for s in sites}        # 6 sites, mais seulement 3 familles distinctes
print(sorted(familles))                            # sorted(...) : un ensemble n'a pas d'ordre, on trie pour l'affichage

2.0
['COM', 'IND', 'RES']


### 💡 Interprétation : Cellule 19, Compréhensions de dictionnaire et d'ensemble

- **`capacite_par_site["SITE_COM_001"]`** : `2.0`. Un dictionnaire retrouve une valeur à partir de sa clé, sans parcourir de liste.
- **Familles** : `['COM', 'IND', 'RES']` ; les six sites donnent trois valeurs, car un ensemble **élimine les doublons**.
- **Équivalent pandas** : `df["site_id"].unique()` joue le même rôle.

## 📝 Cellule 20 : Générateurs : calculer à la demande

In [18]:
# === CELLULE 20 : Générateurs ===

# Avec des parenthèses : rien n'est calculé pour l'instant
gen = (m * 1000 for m in valides)         # les mesures (MW) converties en kW, une par une, à la demande
print(type(gen).__name__)                 # generator : ce n'est pas une liste
print(next(gen))                          # calcule et donne la 1re valeur : 865.0
print(next(gen))                          # la 2e : 1224.0

# Le reste du générateur : list() demande toutes les valeurs restantes
print(list(gen))                          # [149.0, 1105.0] : les deux premières ont déjà été consommées
print(list(gen))                          # [] : un générateur épuisé est vide

# sum() accepte directement un générateur : la somme se calcule sans créer de liste
print(sum(m for m in valides))            # 3.343

generator
865.0
1224.0
[149.0, 1105.0]
[]
3.343


### 💡 Interprétation : Cellule 20, Générateurs : calculer à la demande

- **`generator`** : un objet paresseux ; `next` déclenche **un** calcul à la fois.
- **Épuisement** : après avoir consommé 2 valeurs, `list(gen)` donne les 2 restantes, puis `[]`.
- **`sum(m for m in valides)`** : somme sans liste intermédiaire.
- **Application** : la fonction `lire_csv` (Partie 6) est un générateur : elle lit un fichier de plusieurs Go **ligne par ligne**, sans le charger entièrement.

## 📝 Cellule 21 : Un objet qui se comporte comme une liste : `__len__`, `__getitem__`, `__iter__`, `__contains__`

In [19]:
# === CELLULE 21 : Méthodes magiques d'une collection ===
class ParcSites:
    """Un parc de sites qui se comporte comme une collection Python."""

    def __init__(self, identifiants):         # appelée à la création : ParcSites(liste)
        self._sites = list(identifiants)      # on garde les identifiants dans une liste interne

    def __repr__(self):                       # __repr__ : ce que le notebook affiche pour l'objet
        return f"ParcSites({len(self._sites)} sites)"

    def __len__(self):                        # __len__ : appelée par len(parc)
        return len(self._sites)

    def __getitem__(self, position):          # __getitem__ : appelée par parc[0], parc[-1], parc[1:3]
        return self._sites[position]

    def __iter__(self):                       # __iter__ : appelée par « for site in parc »
        return iter(self._sites)

    def __contains__(self, site_id):          # __contains__ : appelée par « "SITE_X" in parc »
        return site_id in self._sites

parc = ParcSites(sites)                       # « sites » : la liste de six identifiants de la Cellule 15
print(parc)                                   # __repr__ : ParcSites(6 sites)
print(len(parc))                              # __len__ : 6
print(parc[0], "|", parc[-1], "|", parc[1:3]) # __getitem__ : un élément, le dernier, une tranche
print("SITE_COM_001" in parc, "SITE_XXX" in parc)   # __contains__ : True False
print([s for s in parc if s.startswith("SITE_RES")])   # __iter__ : parcours avec une compréhension

ParcSites(6 sites)
6
SITE_IND_001 | SITE_RES_002 | ['SITE_IND_002', 'SITE_COM_001']
True False
['SITE_RES_001', 'SITE_RES_002']


### 💡 Interprétation : Cellule 21, Un objet qui se comporte comme une liste : `__len__`, `__getitem__`, `__iter__`, `__contains__`

- **`ParcSites(6 sites)`** : c'est `__repr__` qui produit ce texte ; sans lui, on verrait une adresse mémoire illisible.
- **`len(parc)` = 6**, **`parc[0]`** = premier site, **`parc[1:3]`** = une tranche : les crochets fonctionnent parce que `__getitem__` existe.
- **`in`** : `"SITE_COM_001" in parc` est vrai, `"SITE_XXX" in parc` est faux.
- **`for`** : la compréhension parcourt le parc grâce à `__iter__`.
- **Lien avec pandas** : `df["colonne"]`, `len(df)`, `for c in df`, `"c" in df` reposent sur ces mêmes quatre méthodes.

---

# PARTIE 4 : FONCTIONS ET CLASSES

---

## 📝 Cellule 22 : Définir une fonction, documenter, retourner

In [20]:
# === CELLULE 22 : Fonctions ===
def taux_charge(conso_mw, capacite_mw):
    """Retourne le taux de charge d'un site (1.0 = 100 % de la capacité)."""   # docstring
    return conso_mw / capacite_mw                       # return : le résultat renvoyé à l'appelant

def statistiques(valeurs):
    """Retourne (minimum, maximum, moyenne) : un tuple de trois valeurs."""
    return min(valeurs), max(valeurs), sum(valeurs) / len(valeurs)

print(taux_charge(2.5, 5.0))                            # 0.5 : appel avec deux arguments
print(taux_charge.__doc__)                              # la docstring est conservée dans l'objet fonction

# « valides » vient de la Cellule 18 ; on déballe le tuple en trois variables
mini, maxi, moyenne = statistiques(valides)
print(mini, maxi, round(moyenne, 3))                    # round(x, 3) : arrondi à 3 décimales

0.5
Retourne le taux de charge d'un site (1.0 = 100 % de la capacité).
0.149 1.224 0.836


### 💡 Interprétation : Cellule 22, Définir une fonction, documenter, retourner

- **`0.5`** : 2,5 MW sur 5 MW = 50 % de la capacité.
- **Docstring** : conservée dans `taux_charge.__doc__`.
- **Tuple** : `mini, maxi, moyenne = ...` déconstruit le résultat en trois variables.
- **Réutilisation** : les fonctions de qualité de données des parties suivantes suivent le même modèle.

## 📝 Cellule 23 : Paramètres nommés et valeurs par défaut

In [21]:
# === CELLULE 23 : Paramètres ===

# « valeur » et « capacite_mw » sont libres ; « arrondi » et « plafond » viennent APRÈS le « * » :
# ils doivent obligatoirement être nommés à l'appel, et ils ont une valeur par défaut.
def normaliser(valeur, capacite_mw, *, arrondi=3, plafond=1.0):
    return round(min(valeur / capacite_mw, plafond), arrondi)   # min(...) plafonne le résultat

print(normaliser(1.224, 2.0))                                   # défauts : arrondi=3, plafond=1.0
print(normaliser(capacite_mw=2.0, valeur=3.0, plafond=0.95))    # nommés, dans un autre ordre

try:
    normaliser(1.224, 2.0, 1)       # ambigu : que représente « 1 » ? Python refuse
except TypeError as erreur:
    print(f"TypeError : {erreur}")

# « / » : conso_mw doit être passé par POSITION ; capacite_mw peut être nommé
def classer(conso_mw, /, capacite_mw):
    return "critique" if conso_mw / capacite_mw >= 0.8 else "normal"

print(classer(1.7, capacite_mw=2.0))                            # critique (1.7 / 2.0 = 85 %)

0.612
0.95
TypeError : normaliser() takes 2 positional arguments but 3 were given
critique


### 💡 Interprétation : Cellule 23, Paramètres nommés et valeurs par défaut

- **`0.612`** : 1,224 / 2,0 arrondi à 3 décimales.
- **`0.95`** : le résultat 1,5 est **plafonné** à 0,95.
- **`TypeError`** : `normaliser(1.224, 2.0, 1)` est ambigu, donc interdit grâce au `*`.
- **Écosystème** : `pd.read_csv(chemin, sep=";", encoding="utf-8")` suit le même principe (options nommées).

## 📝 Cellule 24 : Piège : valeur par défaut mutable

In [22]:
# === CELLULE 24 : Valeur par défaut mutable ===

# ❌ Version piégée : « historique=[] » est créée UNE fois et réutilisée à chaque appel
def enregistrer_erreur_piege(code, historique=[]):
    historique.append(code)
    return historique

print(enregistrer_erreur_piege(-999))     # [-999]
print(enregistrer_erreur_piege(-888))     # on attend [-888] ; on obtient [-999, -888]

# ✅ Version correcte : None par défaut, la liste est créée à chaque appel
def enregistrer_erreur(code, historique=None):
    if historique is None:                # aucun historique fourni : on en crée un neuf
        historique = []
    historique.append(code)
    return historique

print(enregistrer_erreur(-999), enregistrer_erreur(-888))   # [-999] [-888]

[-999]
[-999, -888]
[-999] [-888]


### 💡 Interprétation : Cellule 24, Piège : valeur par défaut mutable

- **Version piégée** : le second appel renvoie `[-999, -888]` : l'historique de l'appel précédent a fui.
- **Version corrigée** : chaque appel repart d'une liste neuve.
- **Règle** : jamais de `[]`, `{}` ou `set()` comme valeur par défaut ; utiliser `None`.

## 📝 Cellule 25 : `*args`, `**kwargs` et dépaquetage

In [23]:
# === CELLULE 25 : *args, **kwargs, dépaquetage ===

# *consos : autant de valeurs que l'on veut ; elles arrivent dans un tuple « consos »
def moyenne_sites(*consos, ignorer=()):
    retenues = [c for c in consos if c not in ignorer]     # on écarte les valeurs à ignorer
    return sum(retenues) / len(retenues)

print(moyenne_sites(0.865, 1.224, -999, ignorer=(-999,)))  # 1.0445 : le -999 est ignoré

# **options : tous les arguments nommés arrivent dans le dictionnaire « options »
def config_lecture(chemin, **options):
    return {"chemin": chemin, **options}                   # ** réinjecte le dictionnaire

options = {"encoding": "utf-8-sig", "sep": ","}
print(config_lecture("data/consommation_echantillon.csv", **options))   # ** à l'appel : un dict devient des arguments nommés

# Déballage étoilé : premier, dernier, et le reste au milieu
premier, *milieu, dernier = sites
print(premier, len(milieu), dernier)                       # SITE_IND_001 4 SITE_RES_002

1.0445
{'chemin': 'data/consommation_echantillon.csv', 'encoding': 'utf-8-sig', 'sep': ','}
SITE_IND_001 4 SITE_RES_002


### 💡 Interprétation : Cellule 25, `*args`, `**kwargs` et dépaquetage

- **`moyenne_sites`** : accepte 3 valeurs ou 30 ; `-999` est écarté.
- **`config_lecture`** : accepte n'importe quelle option et la transmet ; c'est ce que font `pandas.read_csv` et `spark.read.options(...)`.
- **`premier, *milieu, dernier`** : isole les extrémités d'une séquence (`milieu` contient les 4 autres).

## 📝 Cellule 26 : Fusion de dictionnaires : `{**a, **b}` et `|`

In [24]:
# === CELLULE 26 : Fusion de dictionnaires ===

# Les options par défaut, et la surcharge de l'utilisateur (une seule clé change)
defauts = {"encoding": "utf-8-sig", "sep": ","}
perso = {"sep": ";"}

# Hier : chaque ** déverse un dictionnaire dans un nouveau ; la clé « sep » de « perso » écrase l'ancienne
print({**defauts, **perso})       # {'encoding': 'utf-8-sig', 'sep': ';'}

# Aujourd'hui (3.9+) : l'opérateur | fait la même chose, plus lisiblement
print(defauts | perso)            # {'encoding': 'utf-8-sig', 'sep': ';'}

# Les deux écritures donnent le même résultat ; « defauts » n'a pas été modifié
print((defauts | perso) == {**defauts, **perso})   # True
print(defauts)                                     # {'encoding': 'utf-8-sig', 'sep': ','}

{'encoding': 'utf-8-sig', 'sep': ';'}
{'encoding': 'utf-8-sig', 'sep': ';'}
True
{'encoding': 'utf-8-sig', 'sep': ','}


### 💡 Interprétation : Cellule 26, Fusion de dictionnaires : `{**a, **b}` et `|`

- **Résultat** : `encoding` est conservé, `sep` devient `;` : la valeur de `perso` l'emporte.
- **`defauts` reste intact** : la fusion crée un **nouveau** dictionnaire.
- **`|`** : plus lisible que `{**a, **b}` ; disponible depuis Python 3.9.
- **Fabric** : même principe pour fusionner les paramètres par défaut d'un notebook avec ceux transmis par un pipeline.

## 📝 Cellule 27 : Annotations de types

In [25]:
# === CELLULE 27 : Annotations de types ===
from typing import List, Optional

# Hier : il fallait importer List et Optional
def moyenne_v1(valeurs: List[float]) -> Optional[float]:
    return sum(valeurs) / len(valeurs) if valeurs else None    # None si la liste est vide

# Aujourd'hui : « float | None » se lit « un float ou None »
def moyenne_v2(valeurs: list[float]) -> float | None:
    return sum(valeurs) / len(valeurs) if valeurs else None

print(moyenne_v2.__annotations__)              # les annotations sont stockées, sans être vérifiées
print(moyenne_v1([]), moyenne_v2([1.0, 2.0]))  # None 1.5
print(moyenne_v2([1, 2, 3]))                   # des int alors que l'annotation annonce des float : 2.0, aucune erreur

{'valeurs': list[float], 'return': float | None}
None 1.5
2.0


### 💡 Interprétation : Cellule 27, Annotations de types

- **Dernier appel** : passe des `int` alors que l'annotation annonce des `float` ; aucune erreur.
- **Rôle** : documenter et outiller (auto-complétion, détection d'erreurs par l'éditeur), pas contrôler.
- **Compatibilité** : ✅ la forme moderne fonctionne à partir de Python 3.10, donc sur tous les runtimes Fabric actuels.

## 📝 Cellule 28 : `TypedDict` : décrire un enregistrement

In [26]:
# === CELLULE 28 : TypedDict ===
from typing import TypedDict

# Le schéma d'une ligne du CSV : quatre clés, chacune avec son type
class Mesure(TypedDict):
    timestamp: str
    site_id: str
    consumption_mw: float | None      # peut être vide dans le fichier
    status: str

# Un dictionnaire conforme au schéma (l'annotation « : Mesure » le déclare)
exemple: Mesure = {"timestamp": "2025-01-03T04:30:00", "site_id": "SITE_IND_002",
                   "consumption_mw": 0.865, "status": "OK"}
print(exemple["site_id"], list(Mesure.__annotations__))   # les clés déclarées
print(type(exemple).__name__)                             # dict : à l'exécution, rien de spécial

SITE_IND_002 ['timestamp', 'site_id', 'consumption_mw', 'status']
dict


### 💡 Interprétation : Cellule 28, `TypedDict` : décrire un enregistrement

- **Schéma** : les quatre clés et leurs types sont écrits dans le code.
- **`dict`** : à l'exécution, c'est un dictionnaire ordinaire ; aucune vérification.
- **Équivalent Fabric** : un `StructType` Spark ou le schéma d'une table.

## 📝 Cellule 29 : Classe et méthodes magiques : `__init__`, `__repr__`, `__str__`, `__eq__`, `__lt__`

In [27]:
# === CELLULE 29 : Classe et méthodes magiques ===
class Site:
    def __init__(self, site_id, capacite_mw):     # appelée par Site("SITE_IND_001", 5.0)
        self.site_id = site_id                    # « self. » : les données sont rangées dans l'objet
        self.capacite_mw = capacite_mw

    def __repr__(self):                           # texte de diagnostic : ce que le notebook affiche
        return f"Site({self.site_id!r}, {self.capacite_mw})"

    def __str__(self):                            # texte lisible : ce que print() affiche
        return f"{self.site_id} ({self.capacite_mw} MW)"

    def __eq__(self, autre):                      # appelée par « a == b » : deux sites sont égaux si même identifiant
        return isinstance(autre, Site) and self.site_id == autre.site_id

    def __lt__(self, autre):                      # appelée par « a < b » (et par sorted) : on compare les capacités
        return self.capacite_mw < autre.capacite_mw

gros = Site("SITE_IND_001", 5.0)
petit = Site("SITE_RES_002", 0.6)

print(gros)                                       # __str__  : SITE_IND_001 (5.0 MW)
print(repr(gros))                                 # __repr__ : Site('SITE_IND_001', 5.0)
print([gros, petit])                              # une liste affiche les __repr__ de ses éléments
print(gros == Site("SITE_IND_001", 999))          # __eq__ : True (même identifiant, capacité différente)
print(petit < gros)                               # __lt__ : True (0.6 < 5.0)
print(sorted([gros, petit]))                      # sorted utilise __lt__ : du plus petit au plus grand

SITE_IND_001 (5.0 MW)
Site('SITE_IND_001', 5.0)
[Site('SITE_IND_001', 5.0), Site('SITE_RES_002', 0.6)]
True
True
[Site('SITE_RES_002', 0.6), Site('SITE_IND_001', 5.0)]


### 💡 Interprétation : Cellule 29, Classe et méthodes magiques : `__init__`, `__repr__`, `__str__`, `__eq__`, `__lt__`

- **`print(gros)`** : lisible (`__str__`) ; **`repr(gros)`** : reconstructible (`__repr__`).
- **Dans une liste** : Python affiche les `__repr__`, d'où `Site('SITE_RES_002', 0.6)`.
- **`==`** : vrai si les identifiants sont égaux, même avec une capacité différente : c'est **vous** qui définissez ce qu'« égal » veut dire.
- **`sorted`** : trie les objets grâce à `__lt__`, sans `key=`.
- **Lien avec pandas** : un `DataFrame` ou une `Series` affichés dans le notebook sont le résultat d'un `__repr__`.

## 📝 Cellule 30 : `lambda`, tri, `filter`

In [28]:
# === CELLULE 30 : lambda et tri ===
flotte = [{"id": "SITE_IND_001", "cap": 5.0}, {"id": "SITE_COM_002", "cap": 1.5},
          {"id": "SITE_RES_002", "cap": 0.6}, {"id": "SITE_IND_002", "cap": 3.5}]

# key=lambda s: s["cap"] : « pour trier, regarde la clé "cap" de chaque élément »
tri = sorted(flotte, key=lambda s: s["cap"], reverse=True)     # reverse=True : du plus grand au plus petit
print([s["id"] for s in tri])

# Hier : filter garde les éléments pour lesquels la lambda est vraie
grands = list(filter(lambda s: s["cap"] >= 2, flotte))
# Aujourd'hui : la même chose avec une compréhension
grands = [s for s in flotte if s["cap"] >= 2]
print(len(grands))                                              # 2

['SITE_IND_001', 'SITE_IND_002', 'SITE_COM_002', 'SITE_RES_002']
2


### 💡 Interprétation : Cellule 30, `lambda`, tri, `filter`

- **Ordre** : `SITE_IND_001`, `SITE_IND_002`, `SITE_COM_002`, `SITE_RES_002` (par capacité décroissante).
- **`key=lambda ...`** : l'usage le plus fréquent d'une `lambda`.
- **`filter`** : encore vu dans du code ancien ; préférer la compréhension.
- **Limite** : au-delà d'une expression simple, écrire une vraie fonction nommée.

## 📝 Cellule 31 : `partial` et `lru_cache`

In [29]:
# === CELLULE 31 : partial et lru_cache ===
from functools import lru_cache, partial

# partial : « round » avec ndigits=2 déjà rempli ; arrondir_2(x) équivaut à round(x, ndigits=2)
arrondir_2 = partial(round, ndigits=2)
print(arrondir_2(2.34567))                     # 2.35

@lru_cache(maxsize=None)                       # décorateur : mémorise les résultats
def facteur_emission(source):
    print(f"  calcul pour {source}")           # ce message prouve qu'un vrai calcul a lieu
    return {"solaire": 0.032, "eolien": 0.012, "gaz": 0.490}[source]

print(facteur_emission("gaz"), facteur_emission("gaz"))   # deux appels, un seul calcul
print(facteur_emission.cache_info().hits)                 # 1 : nombre de fois où le cache a servi

2.35
  calcul pour gaz
0.49 0.49
1


### 💡 Interprétation : Cellule 31, `partial` et `lru_cache`

- **`calcul pour gaz`** n'apparaît qu'**une fois** : le second appel vient du cache.
- **`cache_info().hits`** vaut `1` : une réponse issue du cache.
- **Utile pour** : une conversion ou une consultation coûteuse appelée des milliers de fois avec les mêmes arguments.

## 📝 Cellule 32 : Portée des variables

In [30]:
# === CELLULE 32 : Portée des variables ===
compteur = 0                                    # variable du niveau supérieur (« globale »)

def incrementer_faux():
    compteur = 1                                # crée une variable LOCALE ; la globale n'est pas touchée
    return compteur

def incrementer():
    global compteur                             # « compteur » désigne ici la variable globale
    compteur += 1
    return compteur

incrementer_faux()
print(compteur)                                 # 0 : inchangé
incrementer()
print(compteur)                                 # 1 : modifié
print("sites" in globals(), "capacite_par_site" in globals())   # les variables des cellules précédentes existent

0
1
True True


### 💡 Interprétation : Cellule 32, Portée des variables

- **`0` puis `1`** : `incrementer_faux` n'a rien modifié ; `incrementer` (avec `global`) l'a fait.
- **Dernière ligne** : les variables des cellules précédentes sont **globales** dans le notebook.
- **Conséquence** : une cellule qui dépend d'une variable créée plus haut échoue après un redémarrage du noyau ; d'où la règle **Restart Kernel and Run All** avant de livrer un notebook.

## 📝 Cellule 33 : Fermetures (closures)

In [31]:
# === CELLULE 33 : Fermetures ===
def fabrique_detecteur(seuil):
    def est_critique(taux):                     # fonction interne
        return taux >= seuil                    # « seuil » vient de la fonction englobante : elle le mémorise
    return est_critique                         # on renvoie la fonction elle-même, sans l'appeler

critique_80 = fabrique_detecteur(0.8)           # une fonction qui se souvient de 0.8
critique_95 = fabrique_detecteur(0.95)          # une autre, qui se souvient de 0.95
print(critique_80(0.85), critique_95(0.85))     # True False : même taux, deux seuils

True False


### 💡 Interprétation : Cellule 33, Fermetures (closures)

- **`True False`** : le même taux (0,85) franchit le seuil de 80 %, pas celui de 95 %.
- **Chaque détecteur garde son seuil.**
- **Suite** : ce mécanisme est à la base des **décorateurs** (comme `@lru_cache`).

## 📝 Cellule 34 : Un objet qu'on appelle comme une fonction : `__call__`

In [32]:
# === CELLULE 34 : __call__ ===
class Detecteur:
    def __init__(self, seuil):
        self.seuil = seuil                       # donnée visible et modifiable
        self.appels = 0                          # compteur d'appels

    def __call__(self, taux):                    # appelée par detecteur(taux)
        self.appels += 1
        return taux >= self.seuil

detecteur = Detecteur(0.8)
print(detecteur(0.85), detecteur(0.5))           # True False : utilisé comme une fonction
print(detecteur.appels, detecteur.seuil)         # 2 0.8 : données lisibles, contrairement à la fermeture
detecteur.seuil = 0.9                            # et modifiables
print(detecteur(0.85))                           # False : le nouveau seuil s'applique
print(callable(detecteur))                       # True : Python le considère comme appelable

True False
2 0.8
False
True


### 💡 Interprétation : Cellule 34, Un objet qu'on appelle comme une fonction : `__call__`

- **`True False`** : l'objet se comporte comme la fonction `critique_80`.
- **`2 0.8`** : on peut lire le nombre d'appels et le seuil, ce que la fermeture cachait.
- **Modifiable** : `detecteur.seuil = 0.9` change le comportement ; la fermeture n'aurait pas permis cela.
- **Rencontrés ensuite** : les modèles de scikit-learn (Atelier 3) sont des objets avec des méthodes ; `pipeline(...)` et les transformations reposent sur le même principe.

# PARTIE 5 : ROBUSTESSE, TEMPS, FICHIERS ET TEXTE

## 📝 Cellule 35 : `try` / `except` / `else` / `finally`

In [33]:
# === CELLULE 35 : Gestion des erreurs ===
def convertir_mesure(texte):
    texte = texte.strip()                        # enlève les espaces autour
    return None if texte == "" else float(texte) # texte vide -> None ; sinon conversion (peut lever ValueError)

def lire_valeur(texte):
    try:
        valeur = convertir_mesure(texte)         # ligne qui peut échouer
    except ValueError:                           # seulement l'erreur attendue : texte non numérique
        print(f"  {texte!r} : illisible")
        return None
    else:                                        # aucune erreur : on renvoie la valeur
        return valeur
    finally:                                     # s'exécute dans TOUS les cas, même après un return
        print(f"  {texte!r} traité")

for brut in ("0.865", "abc", ""):                # une valeur correcte, un texte illisible, une valeur vide
    print(lire_valeur(brut))

  '0.865' traité
0.865
  'abc' : illisible
  'abc' traité
None
  '' traité
None


### 💡 Interprétation : Cellule 35, `try` / `except` / `else` / `finally`

- **`"0.865"`** : convertie en `0.865`.
- **`"abc"`** : `ValueError` capturée, la fonction renvoie `None`.
- **`""`** : renvoie `None` (valeur manquante, pas une erreur).
- **`finally`** : la ligne « traité » apparaît **à chaque fois**, avant le résultat.
- **Règle** : intercepter **uniquement l'erreur attendue** ; un `except Exception` trop large masque de vrais bugs.
- **Suite** : `convertir_mesure` sera déplacée dans un module (Partie 6).

## 📝 Cellule 36 : Erreurs métier et chaînage `raise ... from`

In [34]:
# === CELLULE 36 : raise ... from ===
from datetime import datetime

class TimestampInvalide(ValueError):             # notre erreur métier : hérite de ValueError, corps vide
    """Levée quand un timestamp ne correspond à aucun format connu."""

def horodatage(texte):
    try:
        # strptime : texte -> datetime, selon le format (%Y année, %m mois, %d jour, %H heure, %M minute, %S seconde)
        return datetime.strptime(texte, "%Y-%m-%dT%H:%M:%S")
    except ValueError as erreur:                 # « as erreur » : on récupère l'erreur d'origine
        # On lève notre erreur métier ; « from erreur » garde la cause d'origine
        raise TimestampInvalide(f"Format inconnu : {texte!r}") from erreur

try:
    horodatage("hier soir")                      # ce texte n'est pas une date
except TimestampInvalide as erreur:              # l'appelant n'a besoin de connaître que notre erreur
    print(f"{erreur} <- cause : {erreur.__cause__}")

Format inconnu : 'hier soir' <- cause : time data 'hier soir' does not match format '%Y-%m-%dT%H:%M:%S'


### 💡 Interprétation : Cellule 36, Erreurs métier et chaînage `raise ... from`

- **`Format inconnu : 'hier soir'`** : le message métier, clair.
- **`cause : ...`** : l'erreur technique de `strptime`, conservée.
- **Bénéfice** : l'appelant intercepte `TimestampInvalide` sans connaître `strptime`.

## 📝 Cellule 37 : Groupes d'exceptions : `except*` et `add_note` (3.11)

In [35]:
# === CELLULE 37 : ExceptionGroup, except*, add_note ===
def valider_lot(valeurs):
    erreurs = []                                      # on collecte les erreurs au lieu de s'arrêter
    for i, v in enumerate(valeurs):
        try:
            float(v)
        except ValueError as e:
            e.add_note(f"ligne {i}")                  # on attache le numéro de ligne à l'erreur
            erreurs.append(e)
    if erreurs:
        raise ExceptionGroup("Lot invalide", erreurs) # un seul « raise » pour toutes les erreurs

try:
    valider_lot(["0.5", "x", "1.2", "y"])             # deux valeurs invalides : "x" (ligne 1) et "y" (ligne 3)
except* ValueError as groupe:                         # « except* » : le groupe contient toutes les ValueError
    print(len(groupe.exceptions), "erreurs :", [e.__notes__[0] for e in groupe.exceptions])

2 erreurs : ['ligne 1', 'ligne 3']


### 💡 Interprétation : Cellule 37, Groupes d'exceptions : `except*` et `add_note` (3.11)

- **`2 erreurs : ['ligne 1', 'ligne 3']`** : toutes les erreurs du lot sont rapportées ensemble.
- **Comparaison** : un `try` classique s'arrêterait à la première.
- **Compatibilité** : ✅ Python 3.11+ (Runtime 1.3 inclus) ; à éviter si le code doit tourner sous 3.10.

## 📝 Cellule 38 : Dates : lecture de plusieurs formats

In [36]:
# === CELLULE 38 : Dates — formats multiples ===
from datetime import datetime, timedelta

# Les trois formats présents dans le fichier de mesures
FORMATS_TIMESTAMP = ("%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S", "%d/%m/%Y %H:%M:%S")

def parse_timestamp(texte):
    for fmt in FORMATS_TIMESTAMP:                       # on essaie chaque format à tour de rôle
        try:
            return datetime.strptime(texte.strip(), fmt) # succès : on renvoie tout de suite
        except ValueError:
            continue                                     # échec : format suivant
    raise TimestampInvalide(f"Format inconnu : {texte!r}")  # aucun format ne convient

bruts = ["2025-01-03T04:30:00", "2025-01-03 04:30:00", "03/01/2025 04:30:00"]   # trois écritures du même instant
parses = [parse_timestamp(t) for t in bruts]
print(parses[0], all(p == parses[0] for p in parses))   # all(...) : vrai si TOUTES les comparaisons sont vraies

debut = parses[0]
print(debut + timedelta(minutes=15))                    # ajout d'une durée de 15 minutes
print(debut.strftime("%d/%m/%Y %Hh%M"))                 # datetime -> texte au format français
print(debut.weekday())                                  # jour de la semaine : lundi = 0

2025-01-03 04:30:00 True
2025-01-03 04:45:00
03/01/2025 04h30
4


### 💡 Interprétation : Cellule 38, Dates : lecture de plusieurs formats

- **`True`** : les trois écritures désignent le **même instant**.
- **`04:45:00`** : `timedelta(minutes=15)` a été ajouté.
- **`weekday()` = `4`** : vendredi (lundi = 0).
- **Cas réel** : ce mélange de formats est celui du jeu de données ; la fonction sera réutilisée dans le module.

## 📝 Cellule 39 : Fuseaux horaires et nouveautés 3.11

In [37]:
# === CELLULE 39 : Fuseaux horaires ===
from datetime import UTC
from zoneinfo import ZoneInfo

print(datetime.fromisoformat("2025-01-03T04:30:00Z"))   # « Z » = UTC, accepté depuis 3.11

utc = datetime(2025, 1, 3, 4, 30, tzinfo=UTC)           # 04:30 en UTC, en hiver
paris = utc.astimezone(ZoneInfo("Europe/Paris"))        # même instant, vu à Paris
print(utc.isoformat(), "->", paris.isoformat())

# Même heure UTC, mais en été : Paris est alors à UTC+2
ete = datetime(2025, 7, 3, 4, 30, tzinfo=UTC).astimezone(ZoneInfo("Europe/Paris"))
print(ete.isoformat())

print(datetime.now(UTC).tzinfo)                         # Hier : datetime.utcnow() (déprécié depuis 3.12)

2025-01-03 04:30:00+00:00
2025-01-03T04:30:00+00:00 -> 2025-01-03T05:30:00+01:00
2025-07-03T06:30:00+02:00
UTC


### 💡 Interprétation : Cellule 39, Fuseaux horaires et nouveautés 3.11

- **Hiver** : `04:30 UTC` → `05:30+01:00` à Paris.
- **Été** : `04:30 UTC` → `06:30+02:00` : le décalage change avec l'heure d'été.
- **Règle** : stocker en **UTC**, convertir à l'affichage.
- **Ancien** : `datetime.utcnow()` renvoie une date **sans** fuseau et est dépréciée depuis 3.12.

## 📝 Cellule 40 : Fichiers : `pathlib`

In [38]:
# === CELLULE 40 : pathlib ===
from pathlib import Path

DATA = Path("data")                                                # dossier de données, relatif au dossier courant
print(DATA.exists(), [p.name for p in sorted(DATA.glob("*.csv"))]) # glob("*.csv") : tous les fichiers .csv du dossier

fichier = DATA / "sites_reference.csv"                             # « / » assemble : data/sites_reference.csv
print(fichier.suffix, fichier.stem, fichier.stat().st_size, "octets")   # extension, nom sans extension, taille

True ['consommation_30jours.csv', 'consommation_echantillon.csv', 'sites_reference.csv']
.csv sites_reference 441 octets


### 💡 Interprétation : Cellule 40, Fichiers : `pathlib`

- **`True`** et la liste des deux fichiers CSV du dossier `data`.
- **`.csv`**, **`sites_reference`**, taille en octets.
- **Portabilité** : `Path("data") / "sites_reference.csv"` fonctionne sous Windows (`\`) comme sous Linux (`/`) : c'est ce qui rend un notebook portable vers Fabric.

## 📝 Cellule 41 : Fichiers : lire un CSV et le BOM UTF-8

In [39]:
# === CELLULE 41 : CSV et BOM ===
import csv

print(fichier.read_bytes()[:3])                   # les 3 premiers octets bruts du fichier
with open(fichier, encoding="utf-8") as f:        # ❌ lecture avec « utf-8 » : le BOM reste dans le texte
    print(repr(f.readline()[:12]))                # repr() rend les caractères invisibles visibles

with open(fichier, encoding="utf-8-sig", newline="") as f:   # ✅ « utf-8-sig » retire le BOM
    sites_ref = list(csv.DictReader(f))           # une liste de dictionnaires
print(len(sites_ref), sites_ref[0])

b'\xef\xbb\xbf'
'\ufeffsite_id,sit'
6 {'site_id': 'SITE_IND_001', 'site_type': 'Industrie', 'capacity_mw': '5.0', 'flexible': 'True', 'baseline_mw': '2.5', 'curtailment_price_eur_mwh': '102.0', 'region': 'Ile-de-France'}


### 💡 Interprétation : Cellule 41, Fichiers : lire un CSV et le BOM UTF-8

- **`b'\xef\xbb\xbf'`** : c'est le BOM.
- **Avec `utf-8`** : la première colonne s'appelle `'﻿site_'` ; `ligne["site_id"]` échouerait.
- **Avec `utf-8-sig`** : 6 dictionnaires propres, dont le premier est affiché.
- **Piège fréquent** : les CSV exportés depuis Excel, y compris dans un Lakehouse.

## 📝 Cellule 42 : Un dictionnaire accessible par attributs : `__getattr__`

In [40]:
# === CELLULE 42 : __getattr__ ===
class Enregistrement:
    def __init__(self, donnees):
        self._donnees = donnees                      # le dictionnaire d'origine

    def __getattr__(self, nom):                      # appelée quand « nom » n'est pas un attribut normal
        try:
            return self._donnees[nom]                # on répond avec la clé du dictionnaire
        except KeyError:
            raise AttributeError(f"pas de champ {nom!r}") from None   # attribut inconnu

    def __repr__(self):
        return f"Enregistrement({self._donnees})"

ligne = Enregistrement(sites_ref[0])                 # une ligne du CSV lu à la cellule précédente
print(ligne.site_id, ligne.capacity_mw)              # au lieu de ligne["site_id"], ligne["capacity_mw"]
print(hasattr(ligne, "region"), hasattr(ligne, "inconnu"))   # True False : hasattr s'appuie sur AttributeError

SITE_IND_001 5.0
True False


### 💡 Interprétation : Cellule 42, Un dictionnaire accessible par attributs : `__getattr__`

- **`ligne.site_id`** : lit la clé du dictionnaire, sans crochets.
- **`hasattr`** : `True` pour une colonne existante, `False` sinon.
- **Attention** : `__getattr__` n'est appelée que si l'attribut est **absent** ; les attributs normaux (`_donnees`) passent avant.
- **pandas** : `df.site_id` et `df["site_id"]` sont équivalents.

## 📝 Cellule 43 : Expressions régulières : chercher un motif

In [41]:
# === CELLULE 43 : Expressions régulières — chercher ===
import re

texte = "Alerte 2025-01-03T04:30:00 sur SITE_COM_002 : code -999, puis SITE_IND_001 : code -888"

# Motif d'un identifiant de site : SITE_ + 3 lettres majuscules + _ + 3 chiffres
motif_site = r"SITE_[A-Z]{3}_\d{3}"

m = re.search(motif_site, texte)               # search : le PREMIER résultat, ou None
print(m.group(), "| position", m.start())      # group() : le texte trouvé ; start() : où

print(re.findall(motif_site, texte))           # findall : TOUS les résultats, dans une liste
print(re.findall(r"-\d{3}", texte))            # tous les codes négatifs à 3 chiffres

# Les parenthèses créent des GROUPES : on récupère séparément la famille et le numéro
m = re.search(r"SITE_([A-Z]{3})_(\d{3})", texte)
print(m.groups(), "| famille =", m.group(1))

# fullmatch : le texte ENTIER doit correspondre (validation d'un identifiant)
for candidat in ("SITE_IND_001", "SITE_IND_1", "site_ind_001"):
    print(f"{candidat:<14} valide : {bool(re.fullmatch(motif_site, candidat))}")

SITE_COM_002 | position 31
['SITE_COM_002', 'SITE_IND_001']
['-999', '-888']
('COM', '002') | famille = COM
SITE_IND_001   valide : True
SITE_IND_1     valide : False
site_ind_001   valide : False


### 💡 Interprétation : Cellule 43, Expressions régulières : chercher un motif

- **`SITE_COM_002 | position 31`** : le premier site trouvé et sa position.
- **`findall`** : les deux identifiants `SITE_COM_002`, `SITE_IND_001` ; et les deux codes `-999`, `-888`.
- **Groupes** : `('COM', '002')` ; `group(1)` donne la famille.
- **`fullmatch`** : seul `SITE_IND_001` est valide ; `SITE_IND_1` (un seul chiffre) et `site_ind_001` (minuscules) sont refusés.
- **Usage** : valider des identifiants, extraire des valeurs d'un texte, lire des journaux.

## 📝 Cellule 44 : Expressions régulières : remplacer et classer

In [42]:
# === CELLULE 44 : Expressions régulières — remplacer et classer ===

# --- 1. Remplacer : masquer les codes d'erreur
print(re.sub(r"-\d{3}", "<CODE>", texte))

# --- 2. Réordonner une date : (année)-(mois)-(jour) devient jour/mois/année
#     \1 = année, \2 = mois, \3 = jour
print(re.sub(r"(\d{4})-(\d{2})-(\d{2})", r"\3/\2/\1", "2025-01-03"))

# --- 3. Groupes nommés : lire une ligne de journal dans un dictionnaire
LIGNE = re.compile(r"(?P<ts>\S+) (?P<site>SITE_\w+) (?P<niveau>[A-Z]+) (?P<code>-?\d+)")
extrait = LIGNE.search("2025-01-03T04:30:00 SITE_COM_002 ERROR -999")
print(extrait.groupdict())

# --- 4. Classer les formats de date du vrai fichier de mesures
FORMATS_REGEX = {
    "ISO avec T":      re.compile(r"^\d{4}-\d{2}-\d{2}T"),        # 2025-01-03T04:30:00
    "ISO avec espace": re.compile(r"^\d{4}-\d{2}-\d{2} "),        # 2025-01-03 04:30:00
    "Jour/Mois/Année": re.compile(r"^\d{2}/\d{2}/\d{4} "),        # 03/01/2025 04:30:00
}
with open(DATA / "consommation_echantillon.csv", encoding="utf-8-sig", newline="") as f:
    horodatages = [ligne["timestamp"] for ligne in csv.DictReader(f)]

for nom, motif in FORMATS_REGEX.items():
    print(f"{nom:<16} : {sum(1 for h in horodatages if motif.match(h))} lignes")   # match : motif au DÉBUT du texte

Alerte 2025-01-03T04:30:00 sur SITE_COM_002 : code <CODE>, puis SITE_IND_001 : code <CODE>
03/01/2025
{'ts': '2025-01-03T04:30:00', 'site': 'SITE_COM_002', 'niveau': 'ERROR', 'code': '-999'}
ISO avec T       : 103 lignes
ISO avec espace  : 21 lignes
Jour/Mois/Année  : 26 lignes


### 💡 Interprétation : Cellule 44, Expressions régulières : remplacer et classer

- **`sub`** : `Alerte ... code <CODE>, puis ... code <CODE>`.
- **Date réordonnée** : `2025-01-03` → `03/01/2025`, grâce à `\3/\2/\1`.
- **`groupdict()`** : `{'ts': ..., 'site': 'SITE_COM_002', 'niveau': 'ERROR', 'code': '-999'}` : une ligne de texte devient un enregistrement.
- **Classement** : les trois formats du fichier, avec leur nombre de lignes ; la somme fait **150**.
- **`match` / `search`** : `match` ne cherche qu'**au début** du texte ; `search` cherche partout.
- **Fabric** : PySpark propose les mêmes outils sur des colonnes : `regexp_extract`, `regexp_replace`.

## 📝 Cellule 45 : Fichiers : écrire du JSON, lire du TOML

In [43]:
# === CELLULE 45 : JSON et TOML ===
import json
import tomllib

sortie = Path("out")
sortie.mkdir(exist_ok=True)                                     # crée le dossier « out »
(sortie / "sites.json").write_text(json.dumps(sites_ref, indent=2, ensure_ascii=False), encoding="utf-8")   # objet -> fichier JSON
print(json.loads((sortie / "sites.json").read_text(encoding="utf-8"))[1]["site_id"])                        # fichier JSON -> objet

# On écrit un petit fichier de configuration TOML...
Path("config.toml").write_text('''[chemins]
entree = "data/consommation_echantillon.csv"
sites = "data/sites_reference.csv"

[seuils]
anomalies_max = 0.10
taux_charge_critique = 0.8
''', encoding="utf-8")
# ... puis on le lit (mode binaire obligatoire pour tomllib)
with open("config.toml", "rb") as f:
    config = tomllib.load(f)
print(config["seuils"], type(config["seuils"]["anomalies_max"]).__name__)

SITE_IND_002
{'anomalies_max': 0.1, 'taux_charge_critique': 0.8} float


### 💡 Interprétation : Cellule 45, Fichiers : écrire du JSON, lire du TOML

- **`SITE_IND_002`** : le deuxième site, relu depuis le JSON.
- **TOML** : `0.1` est un `float`, `0.8` aussi ; le type est conservé, contrairement à un CSV où tout est du texte.
- **Intérêt** : séparer les **paramètres** du **code**, comme la cellule de paramètres d'un notebook Fabric.

## 📝 Cellule 46 : Gestionnaire de contexte : `with`, `__enter__`, `__exit__`

In [44]:
# === CELLULE 46 : Gestionnaire de contexte ===
import time

class Chronometre:
    def __enter__(self):                         # appelée à l'entrée du « with »
        self.debut = time.perf_counter()
        self.erreur = None
        return self                              # devient la variable après « as »

    def __exit__(self, type_erreur, erreur, trace):   # appelée à la sortie, même après une erreur
        self.duree = time.perf_counter() - self.debut
        self.erreur = erreur                     # None si tout s'est bien passé
        return False                             # False : l'erreur éventuelle continue de remonter

# Cas normal : on mesure la lecture du fichier
with Chronometre() as chrono:
    lignes_mesures = list(csv.DictReader(open(DATA / "consommation_echantillon.csv", encoding="utf-8-sig", newline="")))
print(len(lignes_mesures), "lignes | durée mesurée :", chrono.duree >= 0)

# Cas d'erreur : __exit__ est appelée quand même
try:
    with Chronometre() as chrono2:
        float("abc")                             # lève une ValueError
except ValueError:
    print("erreur vue par __exit__ :", type(chrono2.erreur).__name__, "| durée mesurée :", chrono2.duree >= 0)

150 lignes | durée mesurée : True
erreur vue par __exit__ : ValueError | durée mesurée : True


### 💡 Interprétation : Cellule 46, Gestionnaire de contexte : `with`, `__enter__`, `__exit__`

- **`150 lignes`** : le fichier lu ; `chrono.duree` a été rempli par `__exit__`.
- **Cas d'erreur** : `__exit__` a bien été appelée et a vu la `ValueError`, avant que celle-ci ne remonte.
- **Même mécanique que `with open(...)`** : le fichier est fermé automatiquement à la sortie.
- **Usage réel** : connexions, verrous, transactions, chronométrage d'une transformation.

## 📝 Cellule 47 : Journalisation avec `logging`

In [45]:
# === CELLULE 47 : logging ===
import logging

# Niveau INFO : les messages DEBUG seront masqués ; « format » décrit la ligne affichée
logging.basicConfig(level=logging.INFO, format="%(levelname)-8s | %(name)s | %(message)s", force=True)
log = logging.getLogger("qualite")                  # un journal nommé

log.debug("Message de mise au point (masqué au niveau INFO)")
log.info("Lecture de %s", config["chemins"]["entree"])            # %s remplacé par le 2e argument
log.warning("%d mesures avec code erreur", 9)
try:
    convertir_mesure("abc")
except ValueError as erreur:
    log.error("Conversion impossible : %s", erreur)

INFO     | qualite | Lecture de data/consommation_echantillon.csv
WARNING  | qualite | 9 mesures avec code erreur
ERROR    | qualite | Conversion impossible : could not convert string to float: 'abc'


### 💡 Interprétation : Cellule 47, Journalisation avec `logging`

- **Message `DEBUG` absent** : le niveau est `INFO`.
- **Production** : niveau `INFO` ; **diagnostic** : `DEBUG`, sans modifier le code.
- **Fabric** : les journaux des notebooks et des pipelines sont consultables dans l'historique d'exécution.

# PARTIE 6 : LES MODULES, POUR RÉUTILISER ET PARTAGER

Toute la journée, vous avez défini des fonctions dans des cellules. Cette dernière partie montre pourquoi et comment les **ranger dans des modules** : vous allez **créer les fichiers vous-même dans l'Explorateur Windows**, pour voir la structure de votre projet, puis les utiliser depuis le notebook.

## 📝 Cellule 48 : Le problème : du code coincé dans le notebook

In [46]:
# === CELLULE 48 : Ce que la session a défini ===

import inspect

# On liste les fonctions et classes définies dans CE notebook (module « __main__ »)
utiles = sorted(nom for nom, obj in globals().items()
                if (inspect.isfunction(obj) or inspect.isclass(obj))     # une fonction ou une classe
                and obj.__module__ == "__main__"                         # définie ici, pas importée
                and obj.__name__ != "<lambda>" and not nom.startswith("_"))
print(len(utiles), "objets définis dans ce notebook :")
print(utiles)

32 objets définis dans ce notebook :
['Chronometre', 'Detecteur', 'Enregistrement', 'Mesure', 'ParcSites', 'Site', 'Statut', 'StatutAncien', 'TimestampInvalide', 'classer', 'config_lecture', 'convertir_mesure', 'critique_80', 'critique_95', 'decrire', 'decrire_ancien', 'enregistrer_erreur', 'enregistrer_erreur_piege', 'fabrique_detecteur', 'horodatage', 'incrementer', 'incrementer_faux', 'lire_valeur', 'moyenne_sites', 'moyenne_v1', 'moyenne_v2', 'normaliser', 'parse_timestamp', 'statistiques', 'taux_charge', 'traiter', 'valider_lot']


### 💡 Interprétation : Cellule 48, Le problème : du code coincé dans le notebook

- **Liste** : `convertir_mesure`, `parse_timestamp`, `lire_valeur`, `Site`, `Detecteur`…
- **Prisonniers de ce notebook** : un autre notebook ou un script planifié devrait les recopier.
- **Objectif de la suite** : déplacer les fonctions **de qualité de données** dans un fichier réutilisable, `energie_utils.py`.

## 🖐️ Étape manuelle : Créer le module `energie_utils.py` (1/2) : constantes et conversions

**Contenu** : les constantes, l'erreur métier, `parse_timestamp` et `convertir_mesure` (les définitions des Cellules 35, 36 et 38, désormais annotées de types).

**À faire** : créer le fichier **à côté du notebook**, dans le dossier de travail (l'emplacement compte : voir Cellule 50).

1. Ouvrez le dossier `formation_python_fabric` dans l'**Explorateur Windows**.
2. Affichez les extensions : onglet **Affichage** → cochez **Extensions de noms de fichiers**. Sans cela, vous créeriez `energie_utils.py.txt` sans le voir.
3. Clic droit dans le dossier → **Nouveau** → **Document texte**. Renommez-le **`energie_utils.py`** (Windows demande de confirmer le changement d'extension : répondez **Oui**).
4. Clic droit sur le fichier → **Ouvrir avec** → **Bloc-notes**. Collez le contenu ci-dessous, puis **Ctrl + S**.
5. Vérifiez l'encodage : **Fichier → Enregistrer sous → Encodage : UTF-8**.

In [47]:
# Étape manuelle : les apprenants créent ce fichier dans l'Explorateur ; ici, création automatique.
with open('energie_utils.py', 'w', encoding='utf-8') as f:
    f.write('"""energie_utils.py — Utilitaires de qualité de données du réseau EnergiaNord."""\nimport csv\nfrom datetime import datetime\nfrom types import MappingProxyType\nfrom typing import Iterator\n\nCODES_ERREUR = MappingProxyType({\n    -999: "Capteur hors service",\n    -888: "Valeur non transmise",\n    -777: "Recalibrage en cours",\n})\n\nFORMATS_TIMESTAMP = (\n    "%Y-%m-%dT%H:%M:%S",\n    "%Y-%m-%d %H:%M:%S",\n    "%d/%m/%Y %H:%M:%S",\n)\n\n\nclass TimestampInvalide(ValueError):\n    """Levée quand un timestamp ne correspond à aucun format connu."""\n\n\ndef parse_timestamp(texte: str) -> datetime:\n    """Convertit un timestamp texte (3 formats possibles) en datetime."""\n    for fmt in FORMATS_TIMESTAMP:\n        try:\n            return datetime.strptime(texte.strip(), fmt)\n        except ValueError:\n            continue\n    raise TimestampInvalide(f"Format inconnu : {texte!r}")\n\n\ndef convertir_mesure(texte: str) -> float | None:\n    """\'\' -> None ; \'0.865\' -> 0.865 ; \'-999\' -> -999.0"""\n    texte = texte.strip()\n    if texte == "":\n        return None\n    return float(texte)\n')
print('energie_utils.py :', len(open('energie_utils.py', encoding='utf-8').read().splitlines()), 'lignes')

energie_utils.py : 39 lignes


## 📝 Cellule 49 : Importer un module

In [48]:
# === CELLULE 49 : Importer energie_utils ===
import importlib
importlib.invalidate_caches()             # le fichier vient d'être créé : on force Python à re-scanner le dossier

import energie_utils                      # charge le module
print(energie_utils.__name__, "|", Path(energie_utils.__file__).name)   # nom du module | fichier source

# Les fonctions définies dans le module (et pas importées d'ailleurs)
print([n for n, o in vars(energie_utils).items()
       if callable(o) and getattr(o, "__module__", None) == "energie_utils"])

from energie_utils import parse_timestamp as lire_date       # import ciblé, avec un alias
print(lire_date("03/01/2025 04:30:00"))
print(energie_utils.CODES_ERREUR[-999])                      # une constante du module, par son nom qualifié

energie_utils | energie_utils.py
['TimestampInvalide', 'parse_timestamp', 'convertir_mesure']
2025-01-03 04:30:00
Capteur hors service


### 💡 Interprétation : Cellule 49, Importer un module

- **`energie_utils | energie_utils.py`** : le module est trouvé et chargé.
- **Contenu** : `TimestampInvalide`, `parse_timestamp`, `convertir_mesure`.
- **Alias** : `lire_date` est `parse_timestamp` sous un autre nom.
- **`Capteur hors service`** : la constante est lue par `energie_utils.CODES_ERREUR`.

## 📝 Cellule 50 : Où Python cherche-t-il un module ?

In [49]:
# === CELLULE 50 : sys.path et modules trouvés ===
import sys
import importlib.util

# La liste ordonnée des dossiers où Python cherche
for rang, dossier in enumerate(sys.path):
    print(rang, dossier)

print()
# Où se trouve energie_utils ? Dans le dossier de travail : le premier de la liste
origine = Path(importlib.util.find_spec("energie_utils").origin)
print("energie_utils.py est dans le dossier courant :", origine.parent == Path.cwd())

# json est dans la bibliothèque standard ; un module qui n'existe nulle part donne None
print(importlib.util.find_spec("json") is not None, importlib.util.find_spec("module_inexistant"))

try:
    import module_inexistant              # introuvable dans tous les dossiers
except ModuleNotFoundError as erreur:
    print(f"ModuleNotFoundError : {erreur}")

0 C:\Users\DELL\AppData\Local\Programs\Python\Python313\python313.zip
1 C:\Users\DELL\AppData\Local\Programs\Python\Python313\DLLs
2 C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib
3 C:\Users\DELL\AppData\Local\Programs\Python\Python313
4 C:\Users\DELL\Desktop\msfabric-minor\Module 1 Python et MS Fabric\formation_python_fabric\.venv-base
5 
6 C:\Users\DELL\Desktop\msfabric-minor\Module 1 Python et MS Fabric\formation_python_fabric\.venv-base\Lib\site-packages

energie_utils.py est dans le dossier courant : True
True None
ModuleNotFoundError : No module named 'module_inexistant'


### 💡 Interprétation : Cellule 50, Où Python cherche-t-il un module ?

- **Entrée 0** : le dossier du notebook ; c'est pourquoi `energie_utils.py` y est trouvé en premier.
- **Entrées suivantes** : la bibliothèque standard, puis le `site-packages` du `.venv`.
- **`energie_utils.py` dans le dossier courant : `True`** : le fichier que vous avez créé est bien celui qui est chargé.
- **`ModuleNotFoundError`** : le module n'existe dans aucun de ces dossiers.
- **Cause fréquente** : le fichier est dans un **autre dossier** que le notebook, ou le `venv` n'est pas activé (le paquet est dans un autre `site-packages`).
- **Fabric** : les fichiers déposés dans les **Resources** du notebook sont placés dans un dossier de ce type.

## 🖐️ Étape manuelle : Compléter `energie_utils.py` (2/2) : qualité et lecture

**Contenu** : `qualifier_mesure` (le `match` de la Cellule 13, appliqué à une mesure) et `lire_csv`, un **générateur** (Cellule 20) : `yield from` passe la main à `DictReader`, ligne par ligne.

**À faire** : **ajouter** ce code à la **fin** du fichier existant, sans rien effacer.

1. Ouvrez `energie_utils.py` avec le **Bloc-notes** (clic droit → **Ouvrir avec**).
2. Placez le curseur à la fin du fichier (**Ctrl + Fin**), appuyez **deux fois** sur **Entrée**.
3. Collez le contenu ci-dessous, puis **Ctrl + S**.

In [50]:
# Étape manuelle : les apprenants créent ce fichier dans l'Explorateur ; ici, création automatique.
with open('energie_utils.py', 'a', encoding='utf-8') as f:
    f.write('\n\ndef qualifier_mesure(valeur: float | None) -> str:\n    """Classe une mesure : MANQUANTE, CODE_ERREUR, NEGATIVE ou VALIDE."""\n    match valeur:\n        case None:\n            return "MANQUANTE"\n        case v if v in CODES_ERREUR:\n            return "CODE_ERREUR"\n        case v if v < 0:\n            return "NEGATIVE"\n        case _:\n            return "VALIDE"\n\n\ndef lire_csv(chemin) -> Iterator[dict]:\n    """Lit un CSV (UTF-8 avec ou sans BOM) et produit un dictionnaire par ligne."""\n    with open(chemin, encoding="utf-8-sig", newline="") as f:\n        yield from csv.DictReader(f)\n')
print('energie_utils.py :', len(open('energie_utils.py', encoding='utf-8').read().splitlines()), 'lignes')

energie_utils.py : 58 lignes


## 📝 Cellule 51 : Le module est en cache : `reload`

In [51]:
# === CELLULE 51 : Modifier un module puis le recharger ===

# Le fichier contient maintenant qualifier_mesure, mais le module en mémoire est l'ancienne version
try:
    from energie_utils import qualifier_mesure
except ImportError as erreur:
    print("Avant reload : ImportError :", str(erreur).split(" (")[0])

importlib.reload(energie_utils)           # relit energie_utils.py depuis le disque

from energie_utils import qualifier_mesure
print("Après reload :", qualifier_mesure(0.865), qualifier_mesure(-999.0), qualifier_mesure(None), qualifier_mesure(-3.2))

Avant reload : ImportError : cannot import name 'qualifier_mesure' from 'energie_utils'
Après reload : VALIDE CODE_ERREUR MANQUANTE NEGATIVE


### 💡 Interprétation : Cellule 51, Le module est en cache : `reload`

- **Avant `reload`** : `ImportError : cannot import name 'qualifier_mesure'` : la session ignore le contenu ajouté.
- **Après `reload`** : `VALIDE CODE_ERREUR MANQUANTE NEGATIVE`.
- **Sans `reload`** : il aurait fallu **redémarrer le noyau**.
- **Workflow typique** : on modifie le module dans l'éditeur, on teste depuis le notebook.

## 📝 Cellule 52 : La bibliothèque standard : des modules déjà installés

In [52]:
# === CELLULE 52 : Modules de la bibliothèque standard ===
from collections import Counter                     # compteur d'occurrences
from statistics import mean, median, stdev          # statistiques simples

from energie_utils import convertir_mesure, lire_csv, qualifier_mesure   # NOTRE module

lignes = list(lire_csv("data/consommation_echantillon.csv"))              # lire_csv est un générateur : list() le consomme
convertis = [convertir_mesure(l["consumption_mw"]) for l in lignes]       # texte -> décimal, ou None
etats = Counter(qualifier_mesure(v) for v in convertis)                   # combien de VALIDE, MANQUANTE...
print(len(lignes), "lignes |", dict(etats))

valeurs = [v for v in convertis if qualifier_mesure(v) == "VALIDE"]       # on ne garde que les valides
print(f"moyenne {mean(valeurs):.3f} | médiane {median(valeurs):.3f} | écart-type {stdev(valeurs):.3f}")

150 lignes | {'VALIDE': 137, 'CODE_ERREUR': 9, 'MANQUANTE': 4}
moyenne 1.134 | médiane 0.953 | écart-type 0.935


### 💡 Interprétation : Cellule 52, La bibliothèque standard : des modules déjà installés

- **Trois modules** suffisent : `collections`, `statistics` et le vôtre.
- **Répartition** : 150 lignes lues, dont 137 `VALIDE`, 9 `CODE_ERREUR` et 4 `MANQUANTE` (les 6 doublons sont encore comptés ici).
- **Statistiques** : moyenne 1,134 MW, médiane 0,953 MW, écart-type 0,935 MW sur les mesures valides.
- **Suite** : tableaux, statistiques avancées et graphiques demandent des paquets externes ; c'est le rôle de `pip`, du venv de la Partie 1 et de l'**Atelier 2**.

## 🖐️ Étape manuelle : Créer `demo_main.py` : l'idiome `main`

**Contenu** : un petit fichier qui affiche la valeur de `__name__` et ses arguments.

1. Ouvrez le dossier `formation_python_fabric` dans l'**Explorateur Windows**.
2. Affichez les extensions : onglet **Affichage** → cochez **Extensions de noms de fichiers**. Sans cela, vous créeriez `demo_main.py.txt` sans le voir.
3. Clic droit dans le dossier → **Nouveau** → **Document texte**. Renommez-le **`demo_main.py`** (Windows demande de confirmer le changement d'extension : répondez **Oui**).
4. Clic droit sur le fichier → **Ouvrir avec** → **Bloc-notes**. Collez le contenu ci-dessous, puis **Ctrl + S**.
5. Vérifiez l'encodage : **Fichier → Enregistrer sous → Encodage : UTF-8**.

In [53]:
# Étape manuelle : les apprenants créent ce fichier dans l'Explorateur ; ici, création automatique.
with open('demo_main.py', 'w', encoding='utf-8') as f:
    f.write('"""Démonstration de l\'idiome main."""\nimport sys\n\n\ndef main(argv=None) -> None:\n    arguments = sys.argv[1:] if argv is None else argv\n    print(f"__name__ vaut : {__name__}")\n    print(f"Arguments     : {arguments}")\n\n\nif __name__ == "__main__":\n    main()\n')
print('demo_main.py :', len(open('demo_main.py', encoding='utf-8').read().splitlines()), 'lignes')

demo_main.py : 12 lignes


## 📝 Cellule 53 : L'idiome `if __name__ == "__main__"`

In [54]:
# === CELLULE 53 : L'idiome main ===
import subprocess

# 1) Exécution comme un SCRIPT (un vrai processus Python)
resultat = subprocess.run([sys.executable, "demo_main.py", "site_1", "--verbose"],
                          capture_output=True, text=True)
print(resultat.stdout)

# 2) Import comme un MODULE : rien ne se lance tout seul
importlib.invalidate_caches()
import demo_main
print(demo_main.__name__)

# 3) On appelle main() nous-mêmes, avec nos propres arguments
demo_main.main(["appel", "depuis", "un", "notebook"])

__name__ vaut : __main__
Arguments     : ['site_1', '--verbose']

demo_main
__name__ vaut : demo_main
Arguments     : ['appel', 'depuis', 'un', 'notebook']


### 💡 Interprétation : Cellule 53, L'idiome `if __name__ == "__main__"`

- **Script** : `__name__ vaut : __main__`, avec les arguments `['site_1', '--verbose']`.
- **Import** : `__name__` vaut `demo_main` ; rien ne s'exécute à l'import.
- **`main([...])`** : la fonction se teste depuis le notebook, sans effet de bord à l'import.

## 📝 Cellule 54 : Arguments de ligne de commande avec `argparse`

In [55]:
# === CELLULE 54 : argparse ===
import argparse

parser = argparse.ArgumentParser(prog="analyse_sites",
                                 description="Contrôle qualité des mesures de consommation")
parser.add_argument("--input", "-i", required=True, help="fichier CSV des mesures")               # obligatoire
parser.add_argument("--seuil", type=float, default=0.10, help="taux d'anomalies maximal toléré")  # converti en float
parser.add_argument("--json", action="store_true", help="écrire aussi un rapport JSON")           # drapeau : vrai s'il est présent

# On simule une ligne de commande avec une liste
args = parser.parse_args(["-i", "data/consommation_echantillon.csv", "--seuil", "0.15", "--json"])
print(args)
print(type(args.seuil).__name__, args.seuil + 1)      # float 1.15 : la conversion a eu lieu

Namespace(input='data/consommation_echantillon.csv', seuil=0.15, json=True)
float 1.15


### 💡 Interprétation : Cellule 54, Arguments de ligne de commande avec `argparse`

- **`Namespace(...)`** : les options lues.
- **`--seuil`** converti en `float` : `0.15`, pas `"0.15"`.
- **Fabric** : cette logique correspond à la **cellule de paramètres** d'un notebook, alimentée par un pipeline.

# PARTIE 6 (suite) : ASSEMBLER LE SCRIPT `analyse_sites.py`

Le script **réutilise** `energie_utils` : il ne redéfinit ni la lecture ni la qualification. Vous le construisez en **trois fichiers-étapes** ; après chacune, une cellule **vérifie** le résultat.

## 🖐️ Étape manuelle : Créer `analyse_sites.py` (1/3) : comptage

**Contenu** : les imports (dont ceux de `energie_utils`) et la fonction `compter`, qui parcourt le fichier, **écarte les doublons** et compte les états par site (`defaultdict(Counter)`, `set` des lignes déjà vues).

1. Ouvrez le dossier `formation_python_fabric` dans l'**Explorateur Windows**.
2. Affichez les extensions : onglet **Affichage** → cochez **Extensions de noms de fichiers**. Sans cela, vous créeriez `analyse_sites.py.txt` sans le voir.
3. Clic droit dans le dossier → **Nouveau** → **Document texte**. Renommez-le **`analyse_sites.py`** (Windows demande de confirmer le changement d'extension : répondez **Oui**).
4. Clic droit sur le fichier → **Ouvrir avec** → **Bloc-notes**. Collez le contenu ci-dessous, puis **Ctrl + S**.
5. Vérifiez l'encodage : **Fichier → Enregistrer sous → Encodage : UTF-8**.

In [57]:
# Étape manuelle : les apprenants créent ce fichier dans l'Explorateur ; ici, création automatique.
with open('analyse_sites.py', 'w', encoding='utf-8') as f:
    f.write('"""analyse_sites.py — Contrôle qualité des mesures de consommation (Atelier 1).\n\nUsage :\n    python analyse_sites.py --input data/consommation_echantillon.csv\n    python analyse_sites.py -i data/consommation_echantillon.csv --seuil 0.05 --json\n"""\nimport argparse\nimport json\nimport logging\nimport sys\nfrom collections import Counter, defaultdict\nfrom pathlib import Path\n\nfrom energie_utils import (TimestampInvalide, convertir_mesure, lire_csv,\n                           parse_timestamp, qualifier_mesure)\n\nlog = logging.getLogger("analyse_sites")\n\n\ndef compter(chemin_mesures: Path) -> dict:\n    """Parcourt le fichier : états par site, somme des valeurs valides, doublons."""\n    vues = set()\n    qualite = defaultdict(Counter)\n    somme_mw = defaultdict(float)\n    doublons = horodatages_invalides = 0\n\n    for ligne in lire_csv(chemin_mesures):\n        cle = tuple(ligne.values())\n        if cle in vues:                       # doublon exact : on l\'écarte\n            doublons += 1\n            continue\n        vues.add(cle)\n\n        try:\n            parse_timestamp(ligne["timestamp"])\n        except TimestampInvalide:\n            horodatages_invalides += 1\n\n        etat = qualifier_mesure(convertir_mesure(ligne["consumption_mw"]))\n        qualite[ligne["site_id"]][etat] += 1\n        if etat == "VALIDE":\n            somme_mw[ligne["site_id"]] += float(ligne["consumption_mw"])\n\n    return {"qualite": qualite, "somme_mw": somme_mw, "doublons": doublons,\n            "horodatages_invalides": horodatages_invalides}\n')
print('analyse_sites.py :', len(open('analyse_sites.py', encoding='utf-8').read().splitlines()), 'lignes')

analyse_sites.py : 45 lignes


## 📝 Cellule 55 : Vérifier l'étape 1 : `compter`

In [58]:
# === CELLULE 55 : Tester compter ===
importlib.invalidate_caches()
import analyse_sites                                          # le fichier vient d'être créé

brut = analyse_sites.compter(Path("data/consommation_echantillon.csv"))
print("doublons écartés      :", brut["doublons"])
print("horodatages invalides :", brut["horodatages_invalides"])
print("SITE_IND_001          :", dict(brut["qualite"]["SITE_IND_001"]))   # états comptés pour un site
print("nombre de sites       :", len(brut["qualite"]))

doublons écartés      : 6
horodatages invalides : 0
SITE_IND_001          : {'VALIDE': 23, 'CODE_ERREUR': 1}
nombre de sites       : 6


### 💡 Interprétation : Cellule 55, Vérifier l'étape 1 : `compter`

- **Doublons** : `6` lignes exactes écartées.
- **Horodatages invalides** : `0` : les trois formats sont tous reconnus.
- **`SITE_IND_001`** : 23 mesures `VALIDE` et 1 `CODE_ERREUR` (24 mesures uniques).
- **Six sites** : le fichier est complet.
- **Bénéfice** : le script **importe** les fonctions de `energie_utils` ; une règle qui change se modifie **une seule fois**.

## 🖐️ Étape manuelle : Compléter `analyse_sites.py` (2/3) : indicateurs par site

**Contenu** : la fonction `analyser`, qui appelle `compter`, lit la **capacité** de chaque site dans `sites_reference.csv`, puis calcule le taux d'anomalies et le taux de charge.

1. Ouvrez `analyse_sites.py` avec le **Bloc-notes** (clic droit → **Ouvrir avec**).
2. Placez le curseur à la fin du fichier (**Ctrl + Fin**), appuyez **deux fois** sur **Entrée**.
3. Collez le contenu ci-dessous, puis **Ctrl + S**.

In [60]:
# Étape manuelle : les apprenants créent ce fichier dans l'Explorateur ; ici, création automatique.
with open('anlyse_sites.py', 'a', encoding='utf-8') as f:
    f.write('\n\ndef analyser(chemin_mesures: Path, chemin_sites: Path) -> dict:\n    """Calcule les indicateurs qualité et charge par site."""\n    sites = {s["site_id"]: s for s in lire_csv(chemin_sites)}\n    brut = compter(chemin_mesures)\n\n    par_site = {}\n    for site_id, compteur in sorted(brut["qualite"].items()):\n        total = sum(compteur.values())\n        valides = compteur["VALIDE"]\n        conso_moyenne = brut["somme_mw"][site_id] / valides if valides else 0.0\n        capacite = float(sites[site_id]["capacity_mw"])\n        par_site[site_id] = {\n            "mesures": total,\n            "valides": valides,\n            "manquantes": compteur["MANQUANTE"],\n            "codes_erreur": compteur["CODE_ERREUR"],\n            "taux_anomalies": round((total - valides) / total, 3),\n            "conso_moyenne_mw": round(conso_moyenne, 3),\n            "taux_charge_moyen": round(conso_moyenne / capacite, 3),\n        }\n\n    total = sum(s["mesures"] for s in par_site.values())\n    anomalies = sum(s["mesures"] - s["valides"] for s in par_site.values())\n    return {\n        "sites": par_site,\n        "doublons_ecartes": brut["doublons"],\n        "horodatages_invalides": brut["horodatages_invalides"],\n        "taux_anomalies_global": round(anomalies / total, 3),\n    }\n')
print('analyse_sites.py :', len(open('analyse_sites.py', encoding='utf-8').read().splitlines()), 'lignes')

analyse_sites.py : 76 lignes


## 📝 Cellule 56 : Vérifier l'étape 2 : `analyser`

In [61]:
# === CELLULE 56 : Tester analyser ===
importlib.reload(analyse_sites)                    # on a ajouté « analyser » dans le fichier

rapport = analyse_sites.analyser(Path("data/consommation_echantillon.csv"), Path("data/sites_reference.csv"))
print(rapport["sites"]["SITE_IND_001"])            # les indicateurs d'un site
print("taux global :", rapport["taux_anomalies_global"])

{'mesures': 24, 'valides': 23, 'manquantes': 0, 'codes_erreur': 1, 'taux_anomalies': 0.042, 'conso_moyenne_mw': 2.619, 'taux_charge_moyen': 0.524}
taux global : 0.09


### 💡 Interprétation : Cellule 56, Vérifier l'étape 2 : `analyser`

- **Dictionnaire d'indicateurs** : mesures, valides, manquantes, codes d'erreur, taux d'anomalies, consommation moyenne, taux de charge moyen.
- **Taux global** : anomalies rapportées à l'ensemble des mesures **uniques** (doublons déjà écartés).
- **Prochaine étape** : présenter ce résultat et en faire un vrai programme en ligne de commande.

## 🖐️ Étape manuelle : Terminer `analyse_sites.py` (3/3) : affichage, arguments, `main`

**Contenu** : `afficher` (tableau), `lire_arguments` (`argparse`), `main` (orchestration, **code de sortie** : `0` = succès, `1` = seuil dépassé) et l'idiome `if __name__ == "__main__"`.

1. Ouvrez `analyse_sites.py` avec le **Bloc-notes** (clic droit → **Ouvrir avec**).
2. Placez le curseur à la fin du fichier (**Ctrl + Fin**), appuyez **deux fois** sur **Entrée**.
3. Collez le contenu ci-dessous, puis **Ctrl + S**.

In [62]:
# Étape manuelle : les apprenants créent ce fichier dans l'Explorateur ; ici, création automatique.
with open('analyse_sites.py', 'a', encoding='utf-8') as f:
    f.write('\n\ndef afficher(rapport: dict) -> None:\n    print(f"{\'Site\':<14}{\'Mesures\':>8}{\'Valides\':>9}{\'Manq.\':>7}{\'Codes\':>7}{\'Anom.\':>8}{\'Charge\':>9}")\n    for site_id, s in rapport["sites"].items():\n        print(f"{site_id:<14}{s[\'mesures\']:>8}{s[\'valides\']:>9}{s[\'manquantes\']:>7}"\n              f"{s[\'codes_erreur\']:>7}{s[\'taux_anomalies\']:>8.1%}{s[\'taux_charge_moyen\']:>9.1%}")\n    print(f"Doublons écartés      : {rapport[\'doublons_ecartes\']}")\n    print(f"Horodatages invalides : {rapport[\'horodatages_invalides\']}")\n    print(f"Taux d\'anomalies      : {rapport[\'taux_anomalies_global\']:.1%}")\n\n\ndef lire_arguments(argv=None) -> argparse.Namespace:\n    parser = argparse.ArgumentParser(prog="analyse_sites", description=__doc__.splitlines()[0])\n    parser.add_argument("--input", "-i", required=True, type=Path, help="fichier CSV des mesures")\n    parser.add_argument("--sites", type=Path, default=Path("data/sites_reference.csv"),\n                        help="référentiel des sites (défaut : %(default)s)")\n    parser.add_argument("--seuil", type=float, default=0.10, help="taux d\'anomalies maximal toléré")\n    parser.add_argument("--json", action="store_true", help="écrire out/rapport_qualite.json")\n    return parser.parse_args(argv)\n\n\ndef main(argv=None) -> int:\n    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")\n    args = lire_arguments(argv)\n\n    log.info("Analyse de %s", args.input)\n    rapport = analyser(args.input, args.sites)\n    afficher(rapport)\n\n    if args.json:\n        Path("out").mkdir(exist_ok=True)\n        Path("out/rapport_qualite.json").write_text(\n            json.dumps(rapport, indent=2, ensure_ascii=False), encoding="utf-8")\n        log.info("Rapport écrit dans out/rapport_qualite.json")\n\n    if rapport["taux_anomalies_global"] > args.seuil:\n        log.error("Seuil dépassé : %.1f %% > %.1f %%",\n                  rapport["taux_anomalies_global"] * 100, args.seuil * 100)\n        return 1\n    log.info("Qualité conforme au seuil")\n    return 0\n\n\nif __name__ == "__main__":\n    sys.exit(main())\n')
print('analyse_sites.py :', len(open('analyse_sites.py', encoding='utf-8').read().splitlines()), 'lignes')

analyse_sites.py : 122 lignes


## 📝 Cellule 57 : Exécuter le script comme en production

In [63]:
# === CELLULE 57 : Lancer analyse_sites.py ===
def lancer(*arguments):
    resultat = subprocess.run([sys.executable, "analyse_sites.py", *arguments],
                              capture_output=True, text=True)
    print(resultat.stdout, end="")                     # sortie normale (le tableau)
    print(resultat.stderr, end="")                     # messages du journal (logging)
    print(f"[code de sortie : {resultat.returncode}]\n")

lancer("--input", "data/consommation_echantillon.csv", "--json")           # seuil par défaut : 10 %
lancer("--input", "data/consommation_echantillon.csv", "--seuil", "0.05")  # seuil strict : 5 %

Site           Mesures  Valides  Manq.  Codes   Anom.   Charge
SITE_COM_001        24       21      0      3   12.5%    45.7%
SITE_COM_002        24       22      1      1    8.3%    44.0%
SITE_IND_001        24       23      0      1    4.2%    52.4%
SITE_IND_002        24       24      0      0    0.0%    49.8%
SITE_RES_001        24       19      3      2   20.8%    46.9%
SITE_RES_002        24       22      0      2    8.3%    46.4%
Doublons écartés      : 6
Horodatages invalides : 0
Taux d'anomalies      : 9.0%
INFO | Analyse de data/consommation_echantillon.csv
INFO | Rapport écrit dans out/rapport_qualite.json
INFO | Qualité conforme au seuil
[code de sortie : 0]



Site           Mesures  Valides  Manq.  Codes   Anom.   Charge
SITE_COM_001        24       21      0      3   12.5%    45.7%
SITE_COM_002        24       22      1      1    8.3%    44.0%
SITE_IND_001        24       23      0      1    4.2%    52.4%
SITE_IND_002        24       24      0      0    0.0%    49.8%
SITE_RES_001        24       19      3      2   20.8%    46.9%
SITE_RES_002        24       22      0      2    8.3%    46.4%
Doublons écartés      : 6
Horodatages invalides : 0
Taux d'anomalies      : 9.0%
INFO | Analyse de data/consommation_echantillon.csv
ERROR | Seuil dépassé : 9.0 % > 5.0 %
[code de sortie : 1]



### 💡 Interprétation : Cellule 57, Exécuter le script comme en production

- **Même données, deux verdicts** : au seuil de 10 %, code `0` ; au seuil de 5 %, le taux global dépasse la tolérance et le code vaut `1`.
- **Pipeline** : il s'appuie sur ce code de sortie pour signaler un échec.
- **`out/rapport_qualite.json`** : produit par la première exécution (option `--json`).

## 📝 Cellule 58 : Pont vers Fabric : un code portable

In [64]:
# === CELLULE 58 : Chemins portables local / Fabric ===
DANS_FABRIC = importlib.util.find_spec("notebookutils") is not None   # True seulement dans Fabric
print(f"Exécution dans Fabric : {DANS_FABRIC}")

def resoudre_chemin(nom_fichier: str) -> Path:
    if DANS_FABRIC:
        return Path("/lakehouse/default/Files/data_python") / nom_fichier   # dossier du Lakehouse
    return Path("data") / nom_fichier                                       # dossier local

chemin = resoudre_chemin("consommation_echantillon.csv")
print(chemin, "| existe :", chemin.exists())

Exécution dans Fabric : False
data/consommation_echantillon.csv | existe : True


### 💡 Interprétation : Cellule 58, Pont vers Fabric : un code portable

- **En local** : `DANS_FABRIC` vaut `False` ; le chemin pointe vers `data/`.
- **Dans Fabric** : le **même** module `energie_utils.py` se dépose dans les **Resources** du notebook ou d'un **Environment**, et s'importe tel quel.
- **Seul l'emplacement des fichiers change**, pas la logique.